project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left: 
      - text: Hands-on Exercises
        menu: 
          - text: Data Wrangling and Choropleth Map (1)
            href: Hands-on_Ex/Hands-on_Ex01.qmd
          - text: Global and Local Measures of Spatial Autocorrelation (2)
            href: Hands-on_Ex/Hands-on_Ex02.qmd
      - text: In-class Exercises
        menu: 
          - text: Spatial Weights and Applications (1)
            href: In-class_Ex/In-class_Ex1/In-class_ex1.qmd
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

