---
title: "Take-home Exercise 1: How Functional are the Water Points in Nigeria?"
editor: visual
execute: 
  warning: false
  message: false
---

## Overview

### Social Context

Water is a critical asset of all communities and nations. It is the core neccessity to sustain the life of both humans and livestock. Lack of access to potable water can lead to serious health hazards and even conflicts between communities and states. According to a 2022 report by World Bank, about 70 million Nigerians do not have access to drinkable water. Access to piped water has decreased from 39% in 1990 to only 11% in 2021. This phenomenon contributes to a surge in violence in Nigeria when communities Fulani herders ad farmers fight over water supplies.

Why is there a water crisis in Nigeria? To gain a perspective on the answer, we will examine the quality and distribution of water supply points in Nigeria.

### Objective

The objective of this exercise is to apply appropriate global and local measures of spatial Association techniques to reveals the spatial patterns of Not Functional water points in Nigeria.

## Setup

### Data

#### Aspatial Data

The aspatial data of water points quality, status and other relevant information is taken from [WPdx Global Data Repositories - WPdx+ version](https://data.waterpointdata.org/dataset/Water-Point-Data-Exchange-Plus-WPdx-/eqje-vguj/data). The data set is downloaded in Shapefile format.

#### Geospatial Data

The geospatial data of Nigeria administrative regions is downloaded from [Geoboundaries](https://www.geoboundaries.org/index.html#getdata). The data level of ADM2, published in 2020, will be used.

### R Packages Used

-   **sf**: used for importing, managing, and processing geospatial data

-   **tidyverse**: a collection of packages for data science tasks

-   **tmap**: used for creating thematic maps, such as choropleth and bubble maps

We load the packages into our working environment using the code below.

```{r}
pacman::p_load(sf, tidyverse, tmap)
```

## Data Wrangling

Aspatial Data
