<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.189">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Sylvia’s Geospatial Journey - Take-home Exercise 2: Regionalisation of Multivariate Water Point Attributes with Non-spatially Constrained and Spatially Constrained Clustering Methods</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Sylvia’s Geospatial Journey</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercises" role="button" data-bs-toggle="dropdown" aria-expanded="false">Hands-on Exercises</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercises">    
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex01.html">
 <span class="dropdown-text">Hands-on Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex02.html">
 <span class="dropdown-text">Hands-on Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex03.html">
 <span class="dropdown-text">Hands-on Exercise 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex04.html">
 <span class="dropdown-text">Hands-on Exercise 4</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-in-class-exercises" role="button" data-bs-toggle="dropdown" aria-expanded="false">In-class Exercises</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-in-class-exercises">    
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex1/In-class_ex1.html">
 <span class="dropdown-text">In-class Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex2/In-class_Ex2.html">
 <span class="dropdown-text">In-class Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex3/In-class_Ex3.html">
 <span class="dropdown-text">In-class Exercise 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex3/In-class_Ex4.qmd">
 <span class="dropdown-text">In-class Exercise 4</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercises" role="button" data-bs-toggle="dropdown" aria-expanded="false">Take-home Exercises</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-take-home-exercises">    
        <li>
    <a class="dropdown-item" href="../../Take-home_Ex/Take-home_Ex1/Take-home_Ex1.html">
 <span class="dropdown-text">Take-home Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Take-home_Ex/Take-home_Ex2/Take-home_Ex2.html">
 <span class="dropdown-text">Take-home Exercise 2</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html">Home</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html">About</a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup">Setup</a>
  <ul class="collapse">
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">Data</a></li>
  <li><a href="#r-packages-used" id="toc-r-packages-used" class="nav-link" data-scroll-target="#r-packages-used">R packages used</a></li>
  </ul></li>
  <li><a href="#data-import-and-preparation" id="toc-data-import-and-preparation" class="nav-link" data-scroll-target="#data-import-and-preparation">Data Import and Preparation</a>
  <ul class="collapse">
  <li><a href="#data-import-and-filter" id="toc-data-import-and-filter" class="nav-link" data-scroll-target="#data-import-and-filter">Data Import and Filter</a></li>
  <li><a href="#data-wrangling" id="toc-data-wrangling" class="nav-link" data-scroll-target="#data-wrangling">Data Wrangling</a></li>
  <li><a href="#performing-point-in-polygon-count" id="toc-performing-point-in-polygon-count" class="nav-link" data-scroll-target="#performing-point-in-polygon-count">Performing Point-in Polygon Count</a></li>
  <li><a href="#checking-duplicate-area-names" id="toc-checking-duplicate-area-names" class="nav-link" data-scroll-target="#checking-duplicate-area-names">Checking duplicate area names</a></li>
  <li><a href="#calculating-the-percentage-of-water-point-values" id="toc-calculating-the-percentage-of-water-point-values" class="nav-link" data-scroll-target="#calculating-the-percentage-of-water-point-values">Calculating the Percentage of Water Point Values</a></li>
  <li><a href="#transforming-to-projected-coordinate-system" id="toc-transforming-to-projected-coordinate-system" class="nav-link" data-scroll-target="#transforming-to-projected-coordinate-system">Transforming to projected coordinate system</a></li>
  <li><a href="#saving-working-data-table" id="toc-saving-working-data-table" class="nav-link" data-scroll-target="#saving-working-data-table">Saving working data table</a></li>
  </ul></li>
  <li><a href="#exploratory-data-analysis-eda" id="toc-exploratory-data-analysis-eda" class="nav-link" data-scroll-target="#exploratory-data-analysis-eda">Exploratory Data Analysis (EDA)</a>
  <ul class="collapse">
  <li><a href="#inspecting-the-distribution-of-the-variables" id="toc-inspecting-the-distribution-of-the-variables" class="nav-link" data-scroll-target="#inspecting-the-distribution-of-the-variables">Inspecting the distribution of the variables</a></li>
  <li><a href="#data-standardization" id="toc-data-standardization" class="nav-link" data-scroll-target="#data-standardization">Data Standardization</a></li>
  <li><a href="#eda-with-choropleth-map" id="toc-eda-with-choropleth-map" class="nav-link" data-scroll-target="#eda-with-choropleth-map">EDA with Choropleth Map</a></li>
  </ul></li>
  <li><a href="#correlation-analysis" id="toc-correlation-analysis" class="nav-link" data-scroll-target="#correlation-analysis">Correlation Analysis</a></li>
  <li><a href="#hierarchy-cluster-analysis" id="toc-hierarchy-cluster-analysis" class="nav-link" data-scroll-target="#hierarchy-cluster-analysis">Hierarchy Cluster Analysis</a>
  <ul class="collapse">
  <li><a href="#extracting-clustering-variables" id="toc-extracting-clustering-variables" class="nav-link" data-scroll-target="#extracting-clustering-variables">Extracting clustering variables</a></li>
  <li><a href="#computing-proximity-matrix" id="toc-computing-proximity-matrix" class="nav-link" data-scroll-target="#computing-proximity-matrix">Computing proximity matrix</a></li>
  <li><a href="#computing-hierarchical-clustering" id="toc-computing-hierarchical-clustering" class="nav-link" data-scroll-target="#computing-hierarchical-clustering">Computing hierarchical clustering</a></li>
  <li><a href="#determining-the-optimal-number-of-clusters" id="toc-determining-the-optimal-number-of-clusters" class="nav-link" data-scroll-target="#determining-the-optimal-number-of-clusters">Determining the optimal number of clusters</a></li>
  <li><a href="#visualizing-hierarchy-clusters-in-choropleth-map" id="toc-visualizing-hierarchy-clusters-in-choropleth-map" class="nav-link" data-scroll-target="#visualizing-hierarchy-clusters-in-choropleth-map">Visualizing hierarchy clusters in choropleth map</a></li>
  </ul></li>
  <li><a href="#spatially-constrained-clustering-skater" id="toc-spatially-constrained-clustering-skater" class="nav-link" data-scroll-target="#spatially-constrained-clustering-skater">Spatially Constrained Clustering: SKATER</a>
  <ul class="collapse">
  <li><a href="#converting-simple-feature-data-frame-into-spatial-polygon-data-frame" id="toc-converting-simple-feature-data-frame-into-spatial-polygon-data-frame" class="nav-link" data-scroll-target="#converting-simple-feature-data-frame-into-spatial-polygon-data-frame">Converting simple feature data frame into spatial polygon data frame</a></li>
  <li><a href="#computing-neighbor-list" id="toc-computing-neighbor-list" class="nav-link" data-scroll-target="#computing-neighbor-list">Computing neighbor list</a></li>
  <li><a href="#computing-minimum-spanning-tree" id="toc-computing-minimum-spanning-tree" class="nav-link" data-scroll-target="#computing-minimum-spanning-tree">Computing minimum spanning tree</a></li>
  <li><a href="#computing-spatially-constrained-clusters-using-skater-method" id="toc-computing-spatially-constrained-clusters-using-skater-method" class="nav-link" data-scroll-target="#computing-spatially-constrained-clusters-using-skater-method">Computing spatially constrained clusters using SKATER method</a></li>
  <li><a href="#visualizing-the-clusters-in-choropleth-map" id="toc-visualizing-the-clusters-in-choropleth-map" class="nav-link" data-scroll-target="#visualizing-the-clusters-in-choropleth-map">Visualizing the clusters in choropleth map</a></li>
  </ul></li>
  <li><a href="#spatially-constrained-clustering-glustgeo-method" id="toc-spatially-constrained-clustering-glustgeo-method" class="nav-link" data-scroll-target="#spatially-constrained-clustering-glustgeo-method">Spatially Constrained Clustering: GlustGeo Method</a></li>
  <li><a href="#comparing-two-clustering-methods" id="toc-comparing-two-clustering-methods" class="nav-link" data-scroll-target="#comparing-two-clustering-methods">Comparing two clustering methods</a></li>
  <li><a href="#multivariate-visualization-of-skater-clusters" id="toc-multivariate-visualization-of-skater-clusters" class="nav-link" data-scroll-target="#multivariate-visualization-of-skater-clusters">Multivariate visualization of SKATER clusters</a></li>
  <li><a href="#conclusion-and-improvement" id="toc-conclusion-and-improvement" class="nav-link" data-scroll-target="#conclusion-and-improvement">Conclusion and Improvement</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Take-home Exercise 2: Regionalisation of Multivariate Water Point Attributes with Non-spatially Constrained and Spatially Constrained Clustering Methods</h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview">Overview</h2>
<p>Take-home Exercise 2 is a continuation of <a href="https://isss624-1stcommit.netlify.app/take-home_ex/take-home_ex1/take-home_ex1">Take-home Exercise 1</a>. In this exercise, we will utilize spatially constrained clustering techniques like SKATER or ClustGeo to conduct the regionalization of Nigeria’s government areas (LGA level - ADM2). The regionalization will be based on the variables below:</p>
<ul>
<li><p>Total number of functional water points</p></li>
<li><p>Total number of nonfunctional water points</p></li>
<li><p>Percentage of functional water points</p></li>
<li><p>Percentage of non-functional water points</p></li>
<li><p>Percentage of main water point technology (i.e.&nbsp;Hand Pump)</p></li>
<li><p>Percentage of usage capacity (i.e.&nbsp;&lt; 1000, &gt;=1000)</p></li>
<li><p>Percentage of rural water points</p></li>
<li><p>Percentage of water source (i.e.&nbsp;Well)</p></li>
</ul>
</section>
<section id="setup" class="level2">
<h2 class="anchored" data-anchor-id="setup">Setup</h2>
<section id="data" class="level3">
<h3 class="anchored" data-anchor-id="data">Data</h3>
<p>The data used in this exercise is the same as in Take-home Exercise 1. More details about the data and its source are mentioned in Take-home Exercise 1. In short, we will use two data sets:</p>
<ul>
<li><p>Geospatial data: the ADM2 data of Nigeria downloaded from Geoboundaries. For simplicity sake, we rename the files to <code>NGA-ADM2</code>.</p></li>
<li><p>Aspatial data: the data of water points in Nigeria is downloaded and filtered from the data set WPdx Global Data Repositories.</p></li>
</ul>
</section>
<section id="r-packages-used" class="level3">
<h3 class="anchored" data-anchor-id="r-packages-used">R packages used</h3>
<ul>
<li><p><strong>sf</strong>: used for importing, managing, and processing geospatial data</p></li>
<li><p><strong>tidyverse</strong>: a collection of packages for data science tasks. It contains the sub-packages dplyr, ggplot2, forcats, tibble, readr, stringr, tidyr, purrr</p></li>
<li><p><strong>tmap</strong>: used for creating thematic maps, such as choropleth and bubble maps</p></li>
<li><p><strong>spdep</strong>: used for calculating spatial dependence - weighting schemes and statistics</p></li>
<li><p><strong>funModeling</strong>: used for EDA and data preparation</p></li>
<li><p><strong>corrplot,</strong> <strong>ggpubr</strong>, <strong>heatmaply</strong>, <strong>factoextra</strong>: multivariate data visualization and analysis</p></li>
<li><p><strong>cluster, ClustGeo</strong>: cluster analysis</p></li>
</ul>
<p>We will load the needed packages into our environment using the code below.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(sf, tidyverse, tmap, spdep, funModeling,</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>               corrplot, ggpubr, heatmaply, factoextra, cluster, ClustGeo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
</section>
<section id="data-import-and-preparation" class="level2">
<h2 class="anchored" data-anchor-id="data-import-and-preparation">Data Import and Preparation</h2>
<p>Repeating what we did in Take-home Exercise 1, we will import the data, filter the data relevant to Nigeria, then conduct data wrangling to prepare for spatially constrained clustering.</p>
<section id="data-import-and-filter" class="level3">
<h3 class="anchored" data-anchor-id="data-import-and-filter">Data Import and Filter</h3>
<section id="aspatial-data" class="level4">
<h4 class="anchored" data-anchor-id="aspatial-data">Aspatial data</h4>
<p>After importing the data, we filter the data related to Nigeria water points using the code chunk below. After that, we save the imported data set into an <code>rds</code> file called <code>wp_nga</code>.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>wp <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"data/aspatial"</span>, <span class="at">layer =</span> <span class="st">"geo_export"</span>, <span class="at">crs =</span> <span class="dv">4326</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(clean_coun <span class="sc">==</span> <span class="st">"Nigeria"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `geo_export' from data source 
  `/Users/sylvia/sylvie-le/ISSS624/Take-home_Ex/Take-home_Ex2/data/aspatial' 
  using driver `ESRI Shapefile'
Simple feature collection with 406566 features and 72 fields
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: -92.05073 ymin: -27.31495 xmax: 92.32694 ymax: 26.65622
Geodetic CRS:  WGS 84</code></pre>
</div>
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(wp, <span class="st">"data/wp_nga.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Next, we reload the Nigeria aspatial data to an object called <code>wp_nga</code>.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>wp_nga <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/wp_nga.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="geospatial-data" class="level4">
<h4 class="anchored" data-anchor-id="geospatial-data">Geospatial data</h4>
<p>We import the geospatial data of Nigeria’s government areas into our environment.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>nga <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"data/geospatial"</span>,</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">layer =</span> <span class="st">"NGA-ADM2"</span>,</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">crs =</span> <span class="dv">4326</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `NGA-ADM2' from data source 
  `/Users/sylvia/sylvie-le/ISSS624/Take-home_Ex/Take-home_Ex2/data/geospatial' 
  using driver `ESRI Shapefile'
Simple feature collection with 774 features and 5 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 2.668534 ymin: 4.273007 xmax: 14.67882 ymax: 13.89442
Geodetic CRS:  WGS 84</code></pre>
</div>
</div>
</section>
</section>
<section id="data-wrangling" class="level3">
<h3 class="anchored" data-anchor-id="data-wrangling">Data Wrangling</h3>
<p>This section is dedicated to examining and transforming the data in <code>wp_nga</code> to include the data regarding water points status, technology, location (urban or rural), and capacity.</p>
<section id="data-distribution" class="level4">
<h4 class="anchored" data-anchor-id="data-distribution">Data distribution</h4>
<p>By inspecting the <code>wp_nga</code> file, we see that the data we want to use for clustering corresponds with the variables below.</p>
<table class="table">
<thead>
<tr class="header">
<th>Data</th>
<th>Variable Name</th>
<th>Data Type/Format</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Water point status</td>
<td><code>status_cle</code></td>
<td>Nominal/String</td>
</tr>
<tr class="even">
<td>Water point technology</td>
<td><code>X_water_tec</code></td>
<td>Nominal/String</td>
</tr>
<tr class="odd">
<td>Water point capacity</td>
<td><code>usage_cap</code></td>
<td>Numeric/Continuous</td>
</tr>
<tr class="even">
<td>Water point location</td>
<td><code>is_urban</code></td>
<td>Boolean</td>
</tr>
</tbody>
</table>
<p>Let’s look at the distribution of the variables by using the functions from <strong>funModeling</strong> package. <code>freq()</code> is used for categorical data, and <code>plot_num()</code> is used for numerical data.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>wpstat <span class="ot">&lt;-</span> <span class="fu">freq</span>(<span class="at">data =</span> wp_nga, <span class="at">input =</span> <span class="st">"status_cle"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Take-home_Ex2_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>wptec <span class="ot">&lt;-</span> <span class="fu">freq</span>(<span class="at">data =</span> wp_nga, <span class="at">input =</span> <span class="st">"X_water_tec"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Take-home_Ex2_files/figure-html/unnamed-chunk-5-2.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>wpcap <span class="ot">&lt;-</span> <span class="fu">hist</span>(wp_nga<span class="sc">$</span>usage_cap, <span class="at">main =</span> <span class="st">"Usage cap distribution"</span>, <span class="at">xlab =</span> <span class="st">"Usage cap"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Take-home_Ex2_files/figure-html/unnamed-chunk-5-3.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>wploc <span class="ot">&lt;-</span> <span class="fu">freq</span>(<span class="at">data =</span> wp_nga, <span class="at">input =</span> <span class="st">"is_urban"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Take-home_Ex2_files/figure-html/unnamed-chunk-5-4.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>While <code>freq()</code> reveal the missing values as NA, <code>hist()</code> allows and omits NA values. Therefore, we need to check NA values for <code>usage_cap</code> with the code chunk below.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>checkna <span class="ot">&lt;-</span> <span class="fu">is.na</span>(wp_nga<span class="sc">$</span>usage_cap)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(checkna)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   Mode   FALSE 
logical   95008 </code></pre>
</div>
</div>
<p>The good news is there is no missing value in <code>usage_cap</code>. We can proceed with our analysis.</p>
</section>
<section id="extracting-functional-data" class="level4">
<h4 class="anchored" data-anchor-id="extracting-functional-data">Extracting functional data</h4>
<p>Using <code>filter()</code> from the <strong>dplyr</strong> package, we filter out the functional values and assign it to a new variable called <code>wpt_functional</code>. This method will be used to extract other data from <code>wp_nga</code>.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>wpt_functional <span class="ot">&lt;-</span> wp_nga <span class="sc">%&gt;%</span> </span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(status_cle <span class="sc">%in%</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>           <span class="fu">c</span>(<span class="st">"Functional"</span>, <span class="st">"Functional but needs repair"</span>,</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>             <span class="st">"Functional but not in use"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="extracting-non-functional-data" class="level4">
<h4 class="anchored" data-anchor-id="extracting-non-functional-data">Extracting non-functional data</h4>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>wpt_nonfunctional <span class="ot">&lt;-</span> wp_nga <span class="sc">%&gt;%</span> </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(status_cle <span class="sc">%in%</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>           <span class="fu">c</span>(<span class="st">"Non-Functional"</span>, <span class="st">"Non-Functional due to dry season"</span>,</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>             <span class="st">"Abandoned/Decommissioned"</span>, <span class="st">"Abandoned"</span>,</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>             <span class="st">"Non functional due to dry season"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="extracting-main-water-point-technology-data" class="level4">
<h4 class="anchored" data-anchor-id="extracting-main-water-point-technology-data">Extracting main water point technology data</h4>
<p>Looking at the distribution of the water point technology, we see that Hand Pump and Mechanized Pump account for the majority of water points technology, 61.84% and 26.99% respectively. We will extract the data containing water points with hand pump technology and mechanized pump technology.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>handpump <span class="ot">&lt;-</span> wp_nga <span class="sc">%&gt;%</span> </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(X_water_tec <span class="sc">==</span> <span class="st">"Hand Pump"</span>)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>mecpump <span class="ot">&lt;-</span> wp_nga <span class="sc">%&gt;%</span> </span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(X_water_tec <span class="sc">==</span> <span class="st">"Mechanized Pump"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="extracting-usage-capacity-data" class="level4">
<h4 class="anchored" data-anchor-id="extracting-usage-capacity-data">Extracting usage capacity data</h4>
<p>Based on the histogram of <code>usage_cap</code>, there are two major range of values that the usage capacity clutters around. The first range is under 400, and the second range is above 800 and less than 1,000. We will use <code>summary()</code> of Base R to inspect in more details.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(wp_nga<span class="sc">$</span>usage_cap)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   50.0   300.0   300.0   488.6  1000.0  1000.0 </code></pre>
</div>
</div>
<p>We will use the threshold of the median, which is 300, to recode <code>usage_cap</code> and form two data range. After recoding, we will also extract usage capacity the data with recoded range. To recode, we will use <code>mutate()</code> and <code>replace()</code> of <strong>dplyr</strong>.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>wp_nga <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/wp_nga.rds"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">usage_cap =</span> <span class="fu">replace</span>(usage_cap, usage_cap <span class="sc">&gt;</span> <span class="dv">300</span>, <span class="st">"Greater than 300"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">usage_cap =</span> <span class="fu">replace</span>(usage_cap, usage_cap <span class="sc">&lt;=</span> <span class="dv">300</span>, <span class="st">"Less than or equal to 300"</span>))</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>cap300_greater <span class="ot">&lt;-</span> wp_nga <span class="sc">%&gt;%</span> <span class="fu">filter</span>(usage_cap <span class="sc">==</span> <span class="st">"Greater than 300"</span>)</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>cap300_less <span class="ot">&lt;-</span> wp_nga <span class="sc">%&gt;%</span> <span class="fu">filter</span>(usage_cap <span class="sc">==</span> <span class="st">"Less than or equal to 300"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="extracting-rural-water-point-data" class="level4">
<h4 class="anchored" data-anchor-id="extracting-rural-water-point-data">Extracting rural water point data</h4>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>ruralwp <span class="ot">&lt;-</span> wp_nga <span class="sc">%&gt;%</span> <span class="fu">filter</span>(is_urban <span class="sc">==</span> <span class="st">"False"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
</section>
<section id="performing-point-in-polygon-count" class="level3">
<h3 class="anchored" data-anchor-id="performing-point-in-polygon-count">Performing Point-in Polygon Count</h3>
<p>Similar to what we did in Take-home Exercise 1, now it is time to group the variables according to which government areas that observation belong to. We will conduct point-in polygon count using <code>st_intersects()</code> of <strong>tmap</strong>.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>nga_wp <span class="ot">&lt;-</span> nga <span class="sc">%&gt;%</span> </span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">total_wp =</span> <span class="fu">lengths</span>(<span class="fu">st_intersects</span>(nga, wp_nga))) <span class="sc">%&gt;%</span> </span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">functional =</span> <span class="fu">lengths</span>(<span class="fu">st_intersects</span>(nga, wpt_functional))) <span class="sc">%&gt;%</span> </span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">nonfunctional =</span> <span class="fu">lengths</span>(<span class="fu">st_intersects</span>(nga, wpt_nonfunctional))) <span class="sc">%&gt;%</span> </span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">hand =</span> <span class="fu">lengths</span>(<span class="fu">st_intersects</span>(nga, handpump))) <span class="sc">%&gt;%</span> </span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">mechanized =</span> <span class="fu">lengths</span>(<span class="fu">st_intersects</span>(nga, mecpump))) <span class="sc">%&gt;%</span> </span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">greater_300_cap =</span> <span class="fu">lengths</span>(<span class="fu">st_intersects</span>(nga, cap300_greater))) <span class="sc">%&gt;%</span> </span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">less_300_cap =</span> <span class="fu">lengths</span>(<span class="fu">st_intersects</span>(nga, cap300_less))) <span class="sc">%&gt;%</span> </span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">rural =</span> <span class="fu">lengths</span>(<span class="fu">st_intersects</span>(nga, ruralwp)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="checking-duplicate-area-names" class="level3">
<h3 class="anchored" data-anchor-id="checking-duplicate-area-names">Checking duplicate area names</h3>
<p>While duplicate area names do not affect spatial weights analysis because it is based on the geometry of the areas, it can affect cluster analysis which is based on the values of the variables. Therefore, we need to check and rename duplicates area names before conducting cluster analysis. To check for duplicates, we will use <code>duplicated()</code> of the <strong>tidyverse</strong> package.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>dupcheck <span class="ot">&lt;-</span> <span class="fu">duplicated</span>(nga_wp<span class="sc">$</span>shapeName)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dupcheck)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   Mode   FALSE    TRUE 
logical     768       6 </code></pre>
</div>
</div>
<p>From the summary, we can see that there are 6 areas with duplicate names. These are the local government areas (LGA) with the same name that belong to different states on the ADM1 level. Using the code chunk below, we extract the names of the duplicated areas, then match them with their corresponding ADM1 in <code>wp_nga</code> states to find out which state they belong to.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>dupnames <span class="ot">&lt;-</span> nga_wp[dupcheck,]<span class="sc">$</span>shapeName</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>dupnames</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Bassa"    "Ifelodun" "Irepodun" "Nasarawa" "Obi"      "Surulere"</code></pre>
</div>
</div>
<p>Now let’s use the duplicated names we extracted to find out the states they belong to. <code>cbind()</code> is used to filter duplicates from multiple columns.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>statenames <span class="ot">&lt;-</span> wp_nga[wp_nga<span class="sc">$</span>clean_adm2 <span class="sc">%in%</span> dupnames, <span class="dv">14</span><span class="sc">:</span><span class="dv">15</span>]</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>statenames <span class="ot">&lt;-</span> statenames[<span class="sc">!</span><span class="fu">duplicated</span>(<span class="fu">cbind</span>(statenames<span class="sc">$</span>clean_adm1, statenames<span class="sc">$</span>clean_adm2)),]</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>statenames</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 12 features and 2 fields
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: 3.355785 ymin: 6.498105 xmax: 8.68657 ymax: 11.98826
Geodetic CRS:  WGS 84
First 10 features:
      clean_adm1 clean_adm2                  geometry
99         Kwara   Irepodun POINT (4.926598 8.107983)
289         Kogi      Bassa POINT (7.063799 7.884609)
863        Lagos   Surulere POINT (3.355785 6.498105)
3778       Benue        Obi POINT (8.332327 6.926308)
7353        Osun   Irepodun POINT (4.490475 7.829663)
7382        Osun   Ifelodun  POINT (4.66123 7.913148)
7640         Oyo   Surulere POINT (4.447453 7.942235)
12445   Nasarawa   Nasarawa POINT (7.837579 7.998326)
15215      Kwara   Ifelodun POINT (4.859352 8.520893)
15345   Nasarawa        Obi POINT (8.670447 8.356312)</code></pre>
</div>
</div>
<p>Now we have a list of 12 duplicated LGAs together with their states. Notice that since we are filtering on <code>wp_nga</code>, the geometry is the location point of a certain water point and not of the LGA. Therefore, we will use <code>st_join()</code> of <strong>sp</strong> package to add the state names into <code>nga_wp</code> based on geometry data. <code>paste()</code> of Base R is used to concatenate the LGA name with their state name in <code>shapeName</code> column, then <code>str_trim()</code> of Base R is used to remove the white space, if any. After we have added the state names to the duplicate LGA names, <code>clean_adm1</code> and <code>clean_adm2</code> column will be removed.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>nga_wp <span class="ot">&lt;-</span> <span class="fu">st_join</span>(nga_wp, statenames) <span class="sc">%&gt;%</span> </span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">clean_adm1 =</span> <span class="fu">replace_na</span>(clean_adm1, <span class="st">" "</span>))</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>nga_wp<span class="sc">$</span>shapeName <span class="ot">&lt;-</span> <span class="fu">str_trim</span>(<span class="fu">paste</span>(nga_wp<span class="sc">$</span>shapeName, nga_wp<span class="sc">$</span>clean_adm1))</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>nga_wp <span class="ot">&lt;-</span> <span class="fu">subset</span>(nga_wp, <span class="at">select =</span> <span class="sc">-</span><span class="fu">c</span>(clean_adm1, clean_adm2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="calculating-the-percentage-of-water-point-values" class="level3">
<h3 class="anchored" data-anchor-id="calculating-the-percentage-of-water-point-values">Calculating the Percentage of Water Point Values</h3>
<p>Absolute measurement of a water point attribute can be affected by the number of water points in an area. For example, an urban area can have a higher number of rural water points than a rural area, simply because it has more water points, while the rural areas does not have many water points to begin with. To offset that effect, we will use percentage measurement. The percentage is calculated over the number of water points having a specific attribute in correspondent with the total number of water points in that government area.</p>
<p>Before we calculate the percentage, it is important to check out the distribution of <code>total_wp</code> because it is the denominator. The code chunk below filters if there is any area that does not have any water points.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>zerowp <span class="ot">&lt;-</span> nga_wp <span class="sc">%&gt;%</span> </span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(total_wp <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>zerowp<span class="sc">$</span>shapeName</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Abadam"     "Bakassi"    "Geidam"     "Gubio"      "Gujba"     
 [6] "Guzamala"   "Kaga"       "Kala/Balge" "Kukawa"     "Madagali"  
[11] "Marte"      "Mobbar"     "Nganzai"   </code></pre>
</div>
</div>
<p>Based on the result, we know that the areas above do not have any water points. As the goal of our cluster analysis is to inspect the areas based on their water point count, the areas with no water points should be removed from our data set. The tasked will be carried out using <code>subset()</code> of Base R.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>nga_wp <span class="ot">&lt;-</span> <span class="fu">subset</span>(nga_wp, total_wp <span class="sc">!=</span> <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Next, we will calcuate the percentage of all variables in <code>nga_wp</code>.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>nga_wp <span class="ot">&lt;-</span> nga_wp <span class="sc">%&gt;%</span> </span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pct_functional =</span> functional<span class="sc">/</span>total_wp<span class="sc">*</span><span class="dv">100</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pct_nonfunctional =</span> nonfunctional<span class="sc">/</span>total_wp<span class="sc">*</span><span class="dv">100</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pct_hand =</span> hand<span class="sc">/</span>total_wp<span class="sc">*</span><span class="dv">100</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pct_mec =</span> mechanized<span class="sc">/</span>total_wp<span class="sc">*</span><span class="dv">100</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pct_greater300 =</span> greater_300_cap<span class="sc">/</span>total_wp<span class="sc">*</span><span class="dv">100</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pct_less300 =</span> less_300_cap<span class="sc">/</span>total_wp<span class="sc">*</span><span class="dv">100</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pct_rural =</span> rural<span class="sc">/</span>total_wp<span class="sc">*</span><span class="dv">100</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Finally, we will remove the unnecessary columns, which are <code>Level</code>, <code>shapeID</code>, <code>shapeGroup</code>, <code>shapeType</code>, <code>hand</code>, <code>mechanized</code>, <code>greater_300_cap</code>, <code>less_300_cap</code>, <code>rural</code>. At the same time, we relocate the <code>geometry</code> column to after <code>shapeName</code> column.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>nga_wp <span class="ot">&lt;-</span> nga_wp[,<span class="sc">-</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">9</span>,<span class="dv">10</span>,<span class="dv">11</span>,<span class="dv">12</span>,<span class="dv">13</span>)] <span class="sc">%&gt;%</span> </span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">relocate</span>(geometry, <span class="at">.after =</span> shapeName)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="transforming-to-projected-coordinate-system" class="level3">
<h3 class="anchored" data-anchor-id="transforming-to-projected-coordinate-system">Transforming to projected coordinate system</h3>
<p>Before proceeding, we need to transform <code>nga_wp</code> into a projected coordinate system. The reason being further analysis involves distance-based calculate, which will not yield correct result if the data is not in the projected coordinate system. To do the transformation task, we will utilize <code>st_transform()</code> from <strong>sf</strong> package. The EPSG code we will convert the data into is <a href="https://epsg.io/26391">EPSG:26391</a>, used for Nigeria West Belt.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>nga_wp <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(nga_wp, <span class="at">crs =</span> <span class="dv">26391</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="saving-working-data-table" class="level3">
<h3 class="anchored" data-anchor-id="saving-working-data-table">Saving working data table</h3>
<p>We will save <code>nga_wp</code> into an rds file using the code below.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(nga_wp, <span class="st">"data/nga_wp.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
</section>
<section id="exploratory-data-analysis-eda" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-data-analysis-eda">Exploratory Data Analysis (EDA)</h2>
<p>Now we can reload the nga_wp_clean.rds file we just saved.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>nga_wp <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/nga_wp.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="inspecting-the-distribution-of-the-variables" class="level3">
<h3 class="anchored" data-anchor-id="inspecting-the-distribution-of-the-variables">Inspecting the distribution of the variables</h3>
<p>Because the variables in consideration are in numerical format, histogram and boxplot are appropriate tools to examine their distribution. Histogram reveals the shape of the distribution, while boxplot show if the variables has outliers and by how many.</p>
<p>To conduct this step. <code>ggplot()</code>, <code>geom_histogram()</code> and <code>geom_boxplot()</code> from <strong>ggplot2</strong> package are utilized.</p>
<section id="functional-water-point-count" class="level4">
<h4 class="anchored" data-anchor-id="functional-water-point-count">Functional water point count</h4>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(nga_wp<span class="sc">$</span>functional)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   0.00   18.00   47.00   68.51   88.00  752.00 </code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>funchis <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> nga_wp, <span class="fu">aes</span>(<span class="at">x =</span> functional)) <span class="sc">+</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">20</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"lightblue"</span>)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>funcbox <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> nga_wp, <span class="fu">aes</span>(<span class="at">x =</span> functional)) <span class="sc">+</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"lightblue"</span>)</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>plotfunc <span class="ot">&lt;-</span> <span class="fu">ggarrange</span>(funchis, funcbox, <span class="at">ncol =</span> <span class="dv">2</span>, <span class="at">nrow =</span> <span class="dv">1</span>)</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a><span class="fu">annotate_figure</span>(plotfunc, <span class="at">top =</span> <span class="fu">text_grob</span>(<span class="st">"Functional Water Points Count"</span>,</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>                <span class="at">face =</span> <span class="st">"bold"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Take-home_Ex2_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="non-functional-water-point-count" class="level4">
<h4 class="anchored" data-anchor-id="non-functional-water-point-count">Non-functional water point count</h4>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(nga_wp<span class="sc">$</span>nonfunctional)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   0.00   14.00   34.00   42.31   61.00  278.00 </code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>nfunchis <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> nga_wp, <span class="fu">aes</span>(<span class="at">x =</span> nonfunctional)) <span class="sc">+</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">20</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"lightblue"</span>)</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>nfuncbox <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> nga_wp, <span class="fu">aes</span>(<span class="at">x =</span> nonfunctional)) <span class="sc">+</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"lightblue"</span>)</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>plotnfunc <span class="ot">&lt;-</span> <span class="fu">ggarrange</span>(nfunchis, nfuncbox, <span class="at">ncol =</span> <span class="dv">2</span>, <span class="at">nrow =</span> <span class="dv">1</span>)</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a><span class="fu">annotate_figure</span>(plotnfunc, <span class="at">top =</span> <span class="fu">text_grob</span>(<span class="st">"Non-functional Water Points Count"</span>,</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>                <span class="at">face =</span> <span class="st">"bold"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Take-home_Ex2_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="functional-water-point-percentage" class="level4">
<h4 class="anchored" data-anchor-id="functional-water-point-percentage">Functional water point percentage</h4>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>funchisp <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> nga_wp, <span class="fu">aes</span>(<span class="at">x =</span> pct_functional)) <span class="sc">+</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">20</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"lightblue"</span>)</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>funcboxp <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> nga_wp, <span class="fu">aes</span>(<span class="at">x =</span> pct_functional)) <span class="sc">+</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"lightblue"</span>)</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>plotfuncp <span class="ot">&lt;-</span> <span class="fu">ggarrange</span>(funchisp, funcboxp, <span class="at">ncol =</span> <span class="dv">2</span>, <span class="at">nrow =</span> <span class="dv">1</span>)</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a><span class="fu">annotate_figure</span>(plotfuncp, <span class="at">top =</span> <span class="fu">text_grob</span>(<span class="st">"Functional Water Points Percentage"</span>,</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>                <span class="at">face =</span> <span class="st">"bold"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Take-home_Ex2_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Since the distribution of <code>pct_functional</code> does not skew too much. We will conduct a fit normal line to find out if the variable follows a normal distribution. The task will be conducted with <code>fitdistr()</code> from <strong>fitdistrplus</strong> package.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(fitdistrplus)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">fitdist</span>(nga_wp<span class="sc">$</span>pct_functional, <span class="st">"norm"</span>)</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Take-home_Ex2_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>From the plots, we can see that <code>pct_functional</code> follows a normal distribution.</p>
</section>
<section id="non-functional-water-point-percentage" class="level4">
<h4 class="anchored" data-anchor-id="non-functional-water-point-percentage">Non-functional water point percentage</h4>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>nfunchisp <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> nga_wp, <span class="fu">aes</span>(<span class="at">x =</span> pct_nonfunctional)) <span class="sc">+</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">20</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"lightblue"</span>)</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>nfuncboxp <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> nga_wp, <span class="fu">aes</span>(<span class="at">x =</span> pct_nonfunctional)) <span class="sc">+</span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"lightblue"</span>)</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>plotnfuncp <span class="ot">&lt;-</span> <span class="fu">ggarrange</span>(nfunchisp, nfuncboxp, <span class="at">ncol =</span> <span class="dv">2</span>, <span class="at">nrow =</span> <span class="dv">1</span>)</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a><span class="fu">annotate_figure</span>(plotnfuncp, <span class="at">top =</span> <span class="fu">text_grob</span>(<span class="st">"Non-functional Water Points Percentage"</span>,</span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>                <span class="at">face =</span> <span class="st">"bold"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Take-home_Ex2_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="hand-pump-water-point-percentage" class="level4">
<h4 class="anchored" data-anchor-id="hand-pump-water-point-percentage">Hand-pump water point percentage</h4>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>handhisp <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> nga_wp, <span class="fu">aes</span>(<span class="at">x =</span> pct_hand)) <span class="sc">+</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">20</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"lightblue"</span>)</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>handboxp <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> nga_wp, <span class="fu">aes</span>(<span class="at">x =</span> pct_hand)) <span class="sc">+</span></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"lightblue"</span>)</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>plothandp <span class="ot">&lt;-</span> <span class="fu">ggarrange</span>(handhisp, handboxp, <span class="at">ncol =</span> <span class="dv">2</span>, <span class="at">nrow =</span> <span class="dv">1</span>)</span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a><span class="fu">annotate_figure</span>(plothandp, <span class="at">top =</span> <span class="fu">text_grob</span>(<span class="st">"Hand Pump Percentage"</span>,</span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>                <span class="at">face =</span> <span class="st">"bold"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Take-home_Ex2_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="mechanized-pump-water-point-percentage" class="level4">
<h4 class="anchored" data-anchor-id="mechanized-pump-water-point-percentage">Mechanized pump water point percentage</h4>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>mechisp <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> nga_wp, <span class="fu">aes</span>(<span class="at">x =</span> pct_mec)) <span class="sc">+</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">20</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"lightblue"</span>)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>mecboxp <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> nga_wp, <span class="fu">aes</span>(<span class="at">x =</span> pct_mec)) <span class="sc">+</span></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"lightblue"</span>)</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>plotmecp <span class="ot">&lt;-</span> <span class="fu">ggarrange</span>(mechisp, mecboxp, <span class="at">ncol =</span> <span class="dv">2</span>, <span class="at">nrow =</span> <span class="dv">1</span>)</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a><span class="fu">annotate_figure</span>(plotmecp, <span class="at">top =</span> <span class="fu">text_grob</span>(<span class="st">"Mechanized Pump Percentage"</span>,</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>                <span class="at">face =</span> <span class="st">"bold"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Take-home_Ex2_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="usage-capacity-greater-than-300-percentage" class="level4">
<h4 class="anchored" data-anchor-id="usage-capacity-greater-than-300-percentage">Usage capacity greater than 300 percentage</h4>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>g300hisp <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> nga_wp, <span class="fu">aes</span>(<span class="at">x =</span> pct_greater300)) <span class="sc">+</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">20</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"lightblue"</span>)</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>g300boxp <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> nga_wp, <span class="fu">aes</span>(<span class="at">x =</span> pct_greater300)) <span class="sc">+</span></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"lightblue"</span>)</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>plotg300p <span class="ot">&lt;-</span> <span class="fu">ggarrange</span>(g300hisp, g300boxp, <span class="at">ncol =</span> <span class="dv">2</span>, <span class="at">nrow =</span> <span class="dv">1</span>)</span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a><span class="fu">annotate_figure</span>(plotg300p, <span class="at">top =</span> <span class="fu">text_grob</span>(<span class="st">"Usage Capacity Greater than 300 Percentage"</span>,</span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>                <span class="at">face =</span> <span class="st">"bold"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Take-home_Ex2_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="usage-capacity-less-than-or-equal-to-300-percentage" class="level4">
<h4 class="anchored" data-anchor-id="usage-capacity-less-than-or-equal-to-300-percentage">Usage capacity less than or equal to 300 percentage</h4>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>l300hisp <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> nga_wp, <span class="fu">aes</span>(<span class="at">x =</span> pct_less300)) <span class="sc">+</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">20</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"lightblue"</span>)</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>l300boxp <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> nga_wp, <span class="fu">aes</span>(<span class="at">x =</span> pct_less300)) <span class="sc">+</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"lightblue"</span>)</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>plotl300p <span class="ot">&lt;-</span> <span class="fu">ggarrange</span>(l300hisp, l300boxp, <span class="at">ncol =</span> <span class="dv">2</span>, <span class="at">nrow =</span> <span class="dv">1</span>)</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a><span class="fu">annotate_figure</span>(plotl300p, <span class="at">top =</span> <span class="fu">text_grob</span>(<span class="st">"Usage Capacity Less than or Equal to 300 Percentage"</span>,</span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>                <span class="at">face =</span> <span class="st">"bold"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Take-home_Ex2_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="rural-water-point-percentage" class="level4">
<h4 class="anchored" data-anchor-id="rural-water-point-percentage">Rural water point percentage</h4>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>ruralhisp <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> nga_wp, <span class="fu">aes</span>(<span class="at">x =</span> pct_rural)) <span class="sc">+</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">20</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"lightblue"</span>)</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>ruralboxp <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> nga_wp, <span class="fu">aes</span>(<span class="at">x =</span> pct_rural)) <span class="sc">+</span></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"lightblue"</span>)</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>plotruralp <span class="ot">&lt;-</span> <span class="fu">ggarrange</span>(ruralhisp, ruralboxp, <span class="at">ncol =</span> <span class="dv">2</span>, <span class="at">nrow =</span> <span class="dv">1</span>)</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a><span class="fu">annotate_figure</span>(plotruralp, <span class="at">top =</span> <span class="fu">text_grob</span>(<span class="st">"Rural Water Point Percentage"</span>,</span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>                <span class="at">face =</span> <span class="st">"bold"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Take-home_Ex2_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="observation" class="level4">
<h4 class="anchored" data-anchor-id="observation">Observation</h4>
<p>Looking at the distribution, we can see that the scale of the variables are within 0 to 100 for all percentage variables. <code>functional</code> and <code>nonfunctional</code> has the maximum value of 752 and 278 respectively. Because the range of <code>functional</code> is very large comparing to the range of other variables, we need to standardize <code>functional</code>.</p>
<blockquote class="blockquote">
<p><strong>Notes:</strong> the distribution of most variables is skewed and does not fit the normal distribution. Therefore, we do not have enough evidence to assume that the variables follow a normal distribution.</p>
</blockquote>
</section>
</section>
<section id="data-standardization" class="level3">
<h3 class="anchored" data-anchor-id="data-standardization">Data Standardization</h3>
<p>We will standardize <code>functional</code> using the Min-Max method. The task is done using <code>normalize()</code> of <strong>heatmaply</strong>. The standardized value is then multiplied by 100 to convert it into the percentage value.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>nga_wp<span class="sc">$</span>functional <span class="ot">=</span> <span class="fu">normalize</span>(nga_wp<span class="sc">$</span>functional)<span class="sc">*</span><span class="dv">100</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="eda-with-choropleth-map" class="level3">
<h3 class="anchored" data-anchor-id="eda-with-choropleth-map">EDA with Choropleth Map</h3>
<p>Choropleth map is used to examine the distribution of attributes over the studied areas. The density of the values is displayed based on the intensity of the color. In the maps below, we will use <code>tm_shape()</code>, <code>tm_borders()</code>, <code>tm_fill()</code> and <code>tm_arrange()</code> from <strong>tmap</strong> package to draw the choropleth map.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>funcmap <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(nga_wp) <span class="sc">+</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">"functional"</span>, <span class="at">n =</span> <span class="dv">5</span>, <span class="at">style =</span> <span class="st">"jenks"</span>, <span class="at">title =</span> <span class="st">"Functional WP"</span>, <span class="at">palette =</span> <span class="st">"GnBu"</span>) <span class="sc">+</span></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">legend.width =</span> <span class="fl">0.3</span>,</span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.height =</span> <span class="fl">0.3</span>,</span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.text.size =</span> <span class="fl">0.5</span>)</span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>nfuncmap <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(nga_wp) <span class="sc">+</span></span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">"nonfunctional"</span>, <span class="at">n =</span> <span class="dv">5</span>, <span class="at">style =</span> <span class="st">"jenks"</span>, <span class="at">title =</span> <span class="st">"Non-functional WP"</span>) <span class="sc">+</span></span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb52-10"><a href="#cb52-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">legend.width =</span> <span class="fl">0.3</span>,</span>
<span id="cb52-11"><a href="#cb52-11" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.height =</span> <span class="fl">0.3</span>,</span>
<span id="cb52-12"><a href="#cb52-12" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.text.size =</span> <span class="fl">0.5</span>)</span>
<span id="cb52-13"><a href="#cb52-13" aria-hidden="true" tabindex="-1"></a>funcpmap <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(nga_wp) <span class="sc">+</span></span>
<span id="cb52-14"><a href="#cb52-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">"pct_functional"</span>, <span class="at">n =</span> <span class="dv">5</span>, <span class="at">style =</span> <span class="st">"jenks"</span>,</span>
<span id="cb52-15"><a href="#cb52-15" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"Functional WP Percentage"</span>, <span class="at">palette =</span> <span class="st">"GnBu"</span>) <span class="sc">+</span></span>
<span id="cb52-16"><a href="#cb52-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb52-17"><a href="#cb52-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">legend.width =</span> <span class="fl">0.3</span>,</span>
<span id="cb52-18"><a href="#cb52-18" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.height =</span> <span class="fl">0.3</span>,</span>
<span id="cb52-19"><a href="#cb52-19" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.text.size =</span> <span class="fl">0.5</span>)</span>
<span id="cb52-20"><a href="#cb52-20" aria-hidden="true" tabindex="-1"></a>nfuncpmap <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(nga_wp) <span class="sc">+</span></span>
<span id="cb52-21"><a href="#cb52-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">"pct_nonfunctional"</span>, <span class="at">n =</span> <span class="dv">5</span>, <span class="at">style =</span> <span class="st">"jenks"</span>, <span class="at">title =</span> <span class="st">"Non-functional WP Percentage"</span>) <span class="sc">+</span></span>
<span id="cb52-22"><a href="#cb52-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb52-23"><a href="#cb52-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">legend.width =</span> <span class="fl">0.3</span>,</span>
<span id="cb52-24"><a href="#cb52-24" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.height =</span> <span class="fl">0.3</span>,</span>
<span id="cb52-25"><a href="#cb52-25" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.text.size =</span> <span class="fl">0.5</span>)</span>
<span id="cb52-26"><a href="#cb52-26" aria-hidden="true" tabindex="-1"></a>handpmap <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(nga_wp) <span class="sc">+</span></span>
<span id="cb52-27"><a href="#cb52-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">"pct_hand"</span>, <span class="at">n =</span> <span class="dv">5</span>, <span class="at">style =</span> <span class="st">"jenks"</span>,</span>
<span id="cb52-28"><a href="#cb52-28" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"Hand Pump Percentage"</span>, <span class="at">palette =</span> <span class="st">"BuPu"</span>) <span class="sc">+</span></span>
<span id="cb52-29"><a href="#cb52-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb52-30"><a href="#cb52-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">legend.width =</span> <span class="fl">0.3</span>,</span>
<span id="cb52-31"><a href="#cb52-31" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.height =</span> <span class="fl">0.3</span>,</span>
<span id="cb52-32"><a href="#cb52-32" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.text.size =</span> <span class="fl">0.5</span>)</span>
<span id="cb52-33"><a href="#cb52-33" aria-hidden="true" tabindex="-1"></a>mecpmap <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(nga_wp) <span class="sc">+</span></span>
<span id="cb52-34"><a href="#cb52-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">"pct_mec"</span>, <span class="at">n =</span> <span class="dv">5</span>, <span class="at">style =</span> <span class="st">"jenks"</span>,</span>
<span id="cb52-35"><a href="#cb52-35" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"Mechanized Pump Percentage"</span>, <span class="at">palette =</span> <span class="st">"BuPu"</span>) <span class="sc">+</span></span>
<span id="cb52-36"><a href="#cb52-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb52-37"><a href="#cb52-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">legend.width =</span> <span class="fl">0.3</span>,</span>
<span id="cb52-38"><a href="#cb52-38" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.height =</span> <span class="fl">0.3</span>,</span>
<span id="cb52-39"><a href="#cb52-39" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.text.size =</span> <span class="fl">0.5</span>)</span>
<span id="cb52-40"><a href="#cb52-40" aria-hidden="true" tabindex="-1"></a>g300pmap <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(nga_wp) <span class="sc">+</span></span>
<span id="cb52-41"><a href="#cb52-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">"pct_greater300"</span>, <span class="at">n =</span> <span class="dv">5</span>, <span class="at">style =</span> <span class="st">"jenks"</span>,</span>
<span id="cb52-42"><a href="#cb52-42" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"&gt;300 Cap Percentage"</span>, <span class="at">palette =</span> <span class="st">"PuBuGn"</span>) <span class="sc">+</span></span>
<span id="cb52-43"><a href="#cb52-43" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb52-44"><a href="#cb52-44" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">legend.width =</span> <span class="fl">0.3</span>,</span>
<span id="cb52-45"><a href="#cb52-45" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.height =</span> <span class="fl">0.3</span>,</span>
<span id="cb52-46"><a href="#cb52-46" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.text.size =</span> <span class="fl">0.5</span>)</span>
<span id="cb52-47"><a href="#cb52-47" aria-hidden="true" tabindex="-1"></a>l300pmap <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(nga_wp) <span class="sc">+</span></span>
<span id="cb52-48"><a href="#cb52-48" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">"pct_less300"</span>, <span class="at">n =</span> <span class="dv">5</span>, <span class="at">style =</span> <span class="st">"jenks"</span>,</span>
<span id="cb52-49"><a href="#cb52-49" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"&lt;=300 Cap Percentage"</span>, <span class="at">palette =</span> <span class="st">"PuBuGn"</span>) <span class="sc">+</span></span>
<span id="cb52-50"><a href="#cb52-50" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb52-51"><a href="#cb52-51" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">legend.width =</span> <span class="fl">0.3</span>,</span>
<span id="cb52-52"><a href="#cb52-52" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.height =</span> <span class="fl">0.3</span>,</span>
<span id="cb52-53"><a href="#cb52-53" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.text.size =</span> <span class="fl">0.5</span>)</span>
<span id="cb52-54"><a href="#cb52-54" aria-hidden="true" tabindex="-1"></a>ruralpmap <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(nga_wp) <span class="sc">+</span></span>
<span id="cb52-55"><a href="#cb52-55" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">"pct_rural"</span>, <span class="at">n =</span> <span class="dv">5</span>, <span class="at">style =</span> <span class="st">"jenks"</span>,</span>
<span id="cb52-56"><a href="#cb52-56" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"Rural Percentage"</span>, <span class="at">palette =</span> <span class="st">"BuGn"</span>) <span class="sc">+</span></span>
<span id="cb52-57"><a href="#cb52-57" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb52-58"><a href="#cb52-58" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">legend.width =</span> <span class="fl">0.3</span>,</span>
<span id="cb52-59"><a href="#cb52-59" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.height =</span> <span class="fl">0.3</span>,</span>
<span id="cb52-60"><a href="#cb52-60" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.text.size =</span> <span class="fl">0.5</span>)</span>
<span id="cb52-61"><a href="#cb52-61" aria-hidden="true" tabindex="-1"></a>total <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(nga_wp) <span class="sc">+</span></span>
<span id="cb52-62"><a href="#cb52-62" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">"total_wp"</span>, <span class="at">n =</span> <span class="dv">5</span>, <span class="at">style =</span> <span class="st">"jenks"</span>,</span>
<span id="cb52-63"><a href="#cb52-63" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"Total water point"</span>, <span class="at">palette =</span> <span class="st">"BrBG"</span>) <span class="sc">+</span></span>
<span id="cb52-64"><a href="#cb52-64" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb52-65"><a href="#cb52-65" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">legend.width =</span> <span class="fl">0.3</span>,</span>
<span id="cb52-66"><a href="#cb52-66" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.height =</span> <span class="fl">0.3</span>,</span>
<span id="cb52-67"><a href="#cb52-67" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.text.size =</span> <span class="fl">0.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(total, ruralpmap, <span class="at">asp =</span> <span class="dv">1</span>, <span class="at">ncol =</span> <span class="dv">2</span>, <span class="at">outer.margins =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Take-home_Ex2_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(funcmap, nfuncmap, <span class="at">asp =</span> <span class="dv">1</span>, <span class="at">ncol =</span> <span class="dv">2</span>, <span class="at">outer.margins =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Take-home_Ex2_files/figure-html/unnamed-chunk-39-2.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(funcpmap, nfuncpmap, <span class="at">asp =</span> <span class="dv">1</span>, <span class="at">ncol =</span> <span class="dv">2</span>, <span class="at">outer.margins =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Take-home_Ex2_files/figure-html/unnamed-chunk-39-3.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(handpmap, mecpmap, <span class="at">asp =</span> <span class="dv">1</span>, <span class="at">ncol =</span> <span class="dv">2</span>, <span class="at">outer.margins =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Take-home_Ex2_files/figure-html/unnamed-chunk-39-4.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(g300pmap, l300pmap, <span class="at">asp =</span> <span class="dv">1</span>, <span class="at">ncol =</span> <span class="dv">2</span>, <span class="at">outer.margins =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Take-home_Ex2_files/figure-html/unnamed-chunk-39-5.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Based on the maps, the distribution of functional and non-functional water points count overlap with total water point count, which is understandable because the higher <code>total_wp</code>, the higher <code>functional</code> and <code>nonfunctional</code>. This similarity decreases as the count is changed to percentage with <code>pct_functional</code> and <code>pct_nonfunctional</code>. As the cluster analysis is sensitive toward correlation, we will not include <code>total_wp</code> into clustering.</p>
<p>In addition, the map of mechanized pump and usage capacity greater than 300 look similar, suggesting correlation. Since correlation will affect clustering, we need to detect and remove other correlated variables.</p>
<p>Notice that the white areas on the map are the LGAs that we removed because they have zero water points.</p>
</section>
</section>
<section id="correlation-analysis" class="level2">
<h2 class="anchored" data-anchor-id="correlation-analysis">Correlation Analysis</h2>
<p>Before we perform cluster analysis, it is important for us to ensure that the cluster variables are not highly correlated. To detect correlation, the best tool is multivariate graph with <code>corrplot.mixed()</code> from <strong>corrplot</strong> package. <code>st_drop_geometry()</code> from <strong>sf</strong> package is used to remove the geometry column and turn <code>nga_wp</code> into a non-spatial data frame.</p>
<blockquote class="blockquote">
<p><strong>Notes:</strong> highly correlated meaning the correlation coefficient is greater than or equal to 0.85.</p>
</blockquote>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>clust.cor <span class="ot">=</span> <span class="fu">cor</span>(<span class="fu">st_drop_geometry</span>(nga_wp[,<span class="dv">4</span><span class="sc">:</span><span class="dv">12</span>]))</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot.mixed</span>(clust.cor,</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">lower =</span> <span class="st">"ellipse"</span>,</span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">upper =</span> <span class="st">"number"</span>,</span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>               <span class="at">tl.pos =</span> <span class="st">"lt"</span>,</span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>               <span class="at">diag =</span> <span class="st">"l"</span>,</span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a>               <span class="at">tl.col =</span> <span class="st">"black"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Take-home_Ex2_files/figure-html/unnamed-chunk-40-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Based on the multivariate correlation table, <code>pct_less300</code> is highly correlated with <code>pct_mec</code> and <code>pct_greater300</code>. <code>pct_mec</code> and <code>pct_greater300</code> are also highly correlated. We will remove <code>pct_less300</code> and <code>pct_mec</code> from our analysis.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>nga_wp <span class="ot">&lt;-</span> nga_wp[,<span class="sc">-</span><span class="fu">c</span>(<span class="dv">9</span>, <span class="dv">11</span>)]</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>clust.cor <span class="ot">=</span> <span class="fu">cor</span>(<span class="fu">st_drop_geometry</span>(nga_wp[,<span class="dv">4</span><span class="sc">:</span><span class="dv">10</span>]))</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot.mixed</span>(clust.cor,</span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">lower =</span> <span class="st">"ellipse"</span>,</span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>               <span class="at">upper =</span> <span class="st">"number"</span>,</span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a>               <span class="at">tl.pos =</span> <span class="st">"lt"</span>,</span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a>               <span class="at">diag =</span> <span class="st">"l"</span>,</span>
<span id="cb59-8"><a href="#cb59-8" aria-hidden="true" tabindex="-1"></a>               <span class="at">tl.col =</span> <span class="st">"black"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Take-home_Ex2_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>After removing <code>pct_less300</code> and <code>pct_mec</code>, our data is no longer highly correlated.</p>
</section>
<section id="hierarchy-cluster-analysis" class="level2">
<h2 class="anchored" data-anchor-id="hierarchy-cluster-analysis">Hierarchy Cluster Analysis</h2>
<section id="extracting-clustering-variables" class="level3">
<h3 class="anchored" data-anchor-id="extracting-clustering-variables">Extracting clustering variables</h3>
<p>To conduct the hierarchy cluster analysis, it is important that we have the right format of data. As the cluster analysis works on the variables values only, we need to extract them from <code>nga_wp_clean</code> simple feature data set. After that, we will set the row names to be the name of the areas.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>clust_var <span class="ot">&lt;-</span> nga_wp[,<span class="sc">-</span><span class="fu">c</span>(<span class="dv">3</span>)] <span class="sc">%&gt;%</span> </span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_set_geometry</span>(<span class="cn">NULL</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Next, we will assign the <code>shapeName</code> column to be the row name column.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">row.names</span>(clust_var) <span class="ot">&lt;-</span> clust_var<span class="sc">$</span>shapeName</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(clust_var)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                    shapeName functional nonfunctional pct_functional
Aba North           Aba North  0.9308511             9       41.17647
Aba South           Aba South  3.8563830            35       40.84507
Abaji                   Abaji  3.0585106            34       40.35088
Abak                     Abak  3.0585106            25       47.91667
Abakaliki           Abakaliki 10.9042553            42       35.19313
Abeokuta North Abeokuta North  2.1276596            15       47.05882
               pct_nonfunctional  pct_hand pct_greater300 pct_rural
Aba North               52.94118 11.764706       82.35294  0.000000
Aba South               49.29577  9.859155       87.32394  5.633803
Abaji                   59.64912 40.350877       59.64912 84.210526
Abak                    52.08333  8.333333       91.66667 83.333333
Abakaliki               18.02575 43.776824        9.44206 87.553648
Abeokuta North          44.11765 14.705882       76.47059 20.588235</code></pre>
</div>
</div>
<p>Lastly, we will remove the <code>shapeName</code> column.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>nigeria_clust <span class="ot">&lt;-</span> clust_var[,<span class="fu">c</span>(<span class="dv">2</span><span class="sc">:</span><span class="dv">8</span>)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="computing-proximity-matrix" class="level3">
<h3 class="anchored" data-anchor-id="computing-proximity-matrix">Computing proximity matrix</h3>
<p>To carry out this task, <code>dist()</code> of base R is used. There are many proximity matrix methods that the function offers. However, we will choose the default method which is “euclidean”.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>proxmat <span class="ot">&lt;-</span> <span class="fu">dist</span>(nigeria_clust, <span class="at">method =</span> <span class="st">'euclidean'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="computing-hierarchical-clustering" class="level3">
<h3 class="anchored" data-anchor-id="computing-hierarchical-clustering">Computing hierarchical clustering</h3>
<p>We will use <code>hclust()</code> of Base R to do this task. Notice that <code>hclust()</code> uses the agglomeration method to compute the cluster. The functions supports eight clustering algorithms: ward.D, ward.D2, single, complete, average(UPGMA), mcquitty(WPGMA), median(WPGMC) and centroid(UPGMC).</p>
<p>First, we need to select the most optimal clustering algorithm.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">c</span>( <span class="st">"average"</span>, <span class="st">"single"</span>, <span class="st">"complete"</span>, <span class="st">"ward"</span>)</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(m) <span class="ot">&lt;-</span> <span class="fu">c</span>( <span class="st">"average"</span>, <span class="st">"single"</span>, <span class="st">"complete"</span>, <span class="st">"ward"</span>)</span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>ac <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">agnes</span>(nigeria_clust, <span class="at">method =</span> x)<span class="sc">$</span>ac</span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb65-7"><a href="#cb65-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-8"><a href="#cb65-8" aria-hidden="true" tabindex="-1"></a><span class="fu">map_dbl</span>(m, ac)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  average    single  complete      ward 
0.8924681 0.8278239 0.9467931 0.9886924 </code></pre>
</div>
</div>
<p>We can see that the ward method provides the strongest clustering structure. Therefore, we will use the ward method to compute the hierarchical clustering as in the code below.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>hclust_ward <span class="ot">&lt;-</span> <span class="fu">hclust</span>(proxmat, <span class="at">method =</span> <span class="st">'ward.D'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="determining-the-optimal-number-of-clusters" class="level3">
<h3 class="anchored" data-anchor-id="determining-the-optimal-number-of-clusters">Determining the optimal number of clusters</h3>
<p>We will use the gap statistic method with the help of <code>clusGap()</code> of the <strong>cluster</strong> package, combined with <code>hcut()</code> function from <strong>extrafacto</strong> package.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">12345</span>)</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>gap_stat <span class="ot">&lt;-</span> <span class="fu">clusGap</span>(nigeria_clust, </span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">FUN =</span> hcut, </span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a>                    <span class="at">nstart =</span> <span class="dv">25</span>, </span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a>                    <span class="at">K.max =</span> <span class="dv">15</span>, </span>
<span id="cb68-6"><a href="#cb68-6" aria-hidden="true" tabindex="-1"></a>                    <span class="at">B =</span> <span class="dv">50</span>)</span>
<span id="cb68-7"><a href="#cb68-7" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(gap_stat, <span class="at">method =</span> <span class="st">"firstmax"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Clustering Gap statistic ["clusGap"] from call:
clusGap(x = nigeria_clust, FUNcluster = hcut, K.max = 15, B = 50, nstart = 25)
B=50 simulated reference sets, k = 1..15; spaceH0="scaledPCA"
 --&gt; Number of clusters (method 'firstmax'): 15
          logW    E.logW       gap      SE.sim
 [1,] 9.815179 10.422963 0.6077839 0.009610740
 [2,] 9.638166 10.297151 0.6589849 0.010574727
 [3,] 9.531530 10.207097 0.6755675 0.010630666
 [4,] 9.444975 10.137891 0.6929163 0.010404717
 [5,] 9.396917 10.105064 0.7081476 0.010156073
 [6,] 9.347167 10.076573 0.7294059 0.009007775
 [7,] 9.286980 10.051022 0.7640420 0.008166518
 [8,] 9.257270 10.027901 0.7706308 0.007931508
 [9,] 9.232442 10.006590 0.7741480 0.008129448
[10,] 9.208196  9.986848 0.7786527 0.008151905
[11,] 9.186749  9.968241 0.7814914 0.008044768
[12,] 9.160007  9.950893 0.7908861 0.007947134
[13,] 9.139783  9.934492 0.7947083 0.008080864
[14,] 9.121686  9.919149 0.7974631 0.008219217
[15,] 9.100932  9.904830 0.8038983 0.008005014</code></pre>
</div>
</div>
<p>Let’s visualize the plot for easier decision making!</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_gap_stat</span>(gap_stat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Take-home_Ex2_files/figure-html/unnamed-chunk-49-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>While 14 is the optimal number of clusters, it is too much to support decision making based on that many clusters. We will choose 8 to be the number of clusters.</p>
<p>Now we can map the 8 clusters with the data table.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>groups <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(<span class="fu">cutree</span>(hclust_ward, <span class="at">k =</span> <span class="dv">8</span>))</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>nigeria_sf_cluster <span class="ot">&lt;-</span> <span class="fu">cbind</span>(nga_wp, <span class="fu">as.matrix</span>(groups)) <span class="sc">%&gt;%</span></span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="st">`</span><span class="at">CLUSTER</span><span class="st">`</span><span class="ot">=</span><span class="st">`</span><span class="at">as.matrix.groups.</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="visualizing-hierarchy-clusters-in-choropleth-map" class="level3">
<h3 class="anchored" data-anchor-id="visualizing-hierarchy-clusters-in-choropleth-map">Visualizing hierarchy clusters in choropleth map</h3>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>hier_clust <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(nigeria_sf_cluster) <span class="sc">+</span> </span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">"CLUSTER"</span>,</span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"Hierarchical Clusters"</span>) <span class="sc">+</span></span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Hierarchical Cluster Map"</span>,</span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.position =</span> <span class="st">"center"</span>,</span>
<span id="cb72-6"><a href="#cb72-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="fl">1.4</span>,</span>
<span id="cb72-7"><a href="#cb72-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.height =</span> <span class="fl">0.25</span>,</span>
<span id="cb72-8"><a href="#cb72-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.width =</span> <span class="fl">0.3</span>,</span>
<span id="cb72-9"><a href="#cb72-9" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.position =</span> <span class="fu">c</span>(<span class="st">"right"</span>, <span class="st">"bottom"</span>),</span>
<span id="cb72-10"><a href="#cb72-10" aria-hidden="true" tabindex="-1"></a>            <span class="at">frame =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb72-11"><a href="#cb72-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>)</span>
<span id="cb72-12"><a href="#cb72-12" aria-hidden="true" tabindex="-1"></a>hier_clust</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Take-home_Ex2_files/figure-html/unnamed-chunk-51-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>There are notes to take here:</p>
<ul>
<li><p>The clusters are dispersing. We can see that there are areas of cluster 8 and cluster 5 being group together, but there are groups that are far away from each other. Other clusters are scattered all around Nigeria. This is because the hierarchical clustering method is not spatially constrained.</p></li>
<li><p>There are some white gaps on the map, which are the zero-water-point LGAs that we removed. To better visualize Nigeria, we can add them back to our mapping data table as a pseudo cluster.</p></li>
</ul>
</section>
</section>
<section id="spatially-constrained-clustering-skater" class="level2">
<h2 class="anchored" data-anchor-id="spatially-constrained-clustering-skater">Spatially Constrained Clustering: SKATER</h2>
<p>SKATER is a spatially constrained clustering method based on the contiguity of the geospatial units. It uses the Tree Edge Removal algorithm to construct minimum spanning tree from adjacency graph, achieving maximum internal homogeneity within the cluster.</p>
<p>To conduct SKATER clustering, there are … steps.</p>
<ol type="1">
<li><p><strong>Convert the simple feature data frame into a spatial polygon data frame.</strong> This is because the SKATER function only works on spatial polygon data frames.</p></li>
<li><p><strong>Compute neighbor list.</strong> The neighbor is defined based on contiguity, also known as shared boundary.</p></li>
<li><p><strong>Compute minimum spanning tree</strong>. The trees are calculated using SKATER function to maximize internal homogeneity.</p></li>
<li><p><strong>Compute spatially constrained clusters.</strong> In this step, we group and assign cluster labels to the area unites.</p></li>
<li><p><strong>Visualize the clusters on the map.</strong> Using the choropleth map, we will display the location of the clusters on the studied area.</p></li>
</ol>
<section id="converting-simple-feature-data-frame-into-spatial-polygon-data-frame" class="level3">
<h3 class="anchored" data-anchor-id="converting-simple-feature-data-frame-into-spatial-polygon-data-frame">Converting simple feature data frame into spatial polygon data frame</h3>
<p>This task is conducted using <code>as_Spatial()</code> from <strong>sp</strong> package.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>wp_sp <span class="ot">&lt;-</span> <span class="fu">as_Spatial</span>(nga_wp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="computing-neighbor-list" class="level3">
<h3 class="anchored" data-anchor-id="computing-neighbor-list">Computing neighbor list</h3>
<p><code>poly2nb()</code> from <strong>spdep</strong> is used to compute the contiguous neighbor list using the QUEEN method.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>wp_nb <span class="ot">&lt;-</span> <span class="fu">poly2nb</span>(wp_sp)</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(wp_nb)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Neighbour list object:
Number of regions: 761 
Number of nonzero links: 4348 
Percentage nonzero weights: 0.750793 
Average number of links: 5.713535 
Link number distribution:

  1   2   3   4   5   6   7   8   9  10  11  12  14 
  4  16  57 122 177 137 121  71  39  11   4   1   1 
4 least connected regions:
138 509 525 560 with 1 link
1 most connected region:
508 with 14 links</code></pre>
</div>
</div>
<p>With the neighbor list, now we can view the neighbor network using <code>plot()</code> from Base R.</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(wp_sp, </span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">border=</span><span class="fu">grey</span>(.<span class="dv">5</span>))</span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(wp_nb, </span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a>     <span class="fu">coordinates</span>(wp_sp), </span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">col=</span><span class="st">"blue"</span>,</span>
<span id="cb76-6"><a href="#cb76-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch =</span> <span class="dv">19</span>,</span>
<span id="cb76-7"><a href="#cb76-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">cex =</span> <span class="fl">0.2</span>,</span>
<span id="cb76-8"><a href="#cb76-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">add=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Take-home_Ex2_files/figure-html/fig1-1.png" class="img-fluid figure-img" width="1440"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="computing-minimum-spanning-tree" class="level3">
<h3 class="anchored" data-anchor-id="computing-minimum-spanning-tree">Computing minimum spanning tree</h3>
<p><code>nbcosts()</code> from spdep package will be used to calculate the cost of each tree, which is the distance between the nodes. This function compute this distance using a data.frame with observations vector in each node.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>lcosts <span class="ot">&lt;-</span> <span class="fu">nbcosts</span>(wp_nb, nigeria_clust)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>When viewing <code>lcosts</code>, we notice that it has the pairwise dissimilarity of the variables between a specific LGA and its neighbors. Next, we will compute a weight matrix based on the data of <code>lcosts</code>, treated as the weight. The “binary” style is chosen for the weight calculation as it is more robust.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>nigeria.w <span class="ot">&lt;-</span> <span class="fu">nb2listw</span>(wp_nb,</span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>                      lcosts,</span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">style =</span> <span class="st">"B"</span>)</span>
<span id="cb78-4"><a href="#cb78-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(nigeria.w)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Characteristics of weights list object:
Neighbour list object:
Number of regions: 761 
Number of nonzero links: 4348 
Percentage nonzero weights: 0.750793 
Average number of links: 5.713535 
Link number distribution:

  1   2   3   4   5   6   7   8   9  10  11  12  14 
  4  16  57 122 177 137 121  71  39  11   4   1   1 
4 least connected regions:
138 509 525 560 with 1 link
1 most connected region:
508 with 14 links

Weights style: B 
Weights constants summary:
    n     nn       S0       S1        S2
B 761 579121 269330.2 43789952 481971405</code></pre>
</div>
</div>
<p>Next, we will use <code>mstree()</code> of <strong>spdep</strong> package to compute the minimum spanning tree.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>nigeria.mst <span class="ot">&lt;-</span> <span class="fu">mstree</span>(nigeria.w)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Now we can plot the tree networks and their nodes onto Nigeria map.</p>
<div class="cell" data-layout-align="center">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(wp_sp, <span class="at">border=</span><span class="fu">gray</span>(.<span class="dv">5</span>))</span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot.mst</span>(nigeria.mst, </span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a>         <span class="fu">coordinates</span>(wp_sp), </span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">col=</span><span class="st">"blue"</span>, </span>
<span id="cb81-5"><a href="#cb81-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">cex.lab=</span><span class="fl">0.7</span>, </span>
<span id="cb81-6"><a href="#cb81-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">cex.circles=</span><span class="fl">0.005</span>, </span>
<span id="cb81-7"><a href="#cb81-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">add=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Take-home_Ex2_files/figure-html/fig2-1.png" class="img-fluid figure-img" width="1920"></p>
</figure>
</div>
</div>
</div>
<p>Since our data set has more than 700 observations, presenting the minimum spanning tree on the map produces a lot of clutter nodes and overlapping text. From now on, we will only present the clusters using the choropleth map.</p>
</section>
<section id="computing-spatially-constrained-clusters-using-skater-method" class="level3">
<h3 class="anchored" data-anchor-id="computing-spatially-constrained-clusters-using-skater-method">Computing spatially constrained clusters using SKATER method</h3>
<p>We will use <code>skater()</code> from spdep package to compute the spatially constrained clusters. Based on the analysis in Hierarchical Clustering, we will choose the number of cluster to be 8.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>clust8 <span class="ot">&lt;-</span> spdep<span class="sc">::</span><span class="fu">skater</span>(<span class="at">edges =</span> nigeria.mst[,<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>],</span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>                        <span class="at">data =</span> nigeria_clust,</span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a>                        <span class="at">method =</span> <span class="st">"euclidean"</span>,</span>
<span id="cb82-4"><a href="#cb82-4" aria-hidden="true" tabindex="-1"></a>                        <span class="at">ncuts =</span> <span class="dv">7</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Now we can plot the choropleth map for the clusters!</p>
</section>
<section id="visualizing-the-clusters-in-choropleth-map" class="level3">
<h3 class="anchored" data-anchor-id="visualizing-the-clusters-in-choropleth-map">Visualizing the clusters in choropleth map</h3>
<p>First, let’s compute the clusters and their corresponding geometry. We will call it <code>nigeria_spatialcluster</code>.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>groups_mat <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(clust8<span class="sc">$</span>groups)</span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>nigeria_spatialcluster <span class="ot">&lt;-</span> <span class="fu">cbind</span>(nigeria_sf_cluster, <span class="fu">as.factor</span>(groups_mat)) <span class="sc">%&gt;%</span></span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="st">`</span><span class="at">SP_CLUSTER</span><span class="st">`</span><span class="ot">=</span><span class="st">`</span><span class="at">as.factor.groups_mat.</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Notice that <code>nigeria_spatialcluster</code> is calculated based on <code>nga_wp_clean</code>, which does not contain the areas that have no water point. For the sake of visualization, we will add those areas back to our spatial clustering data and set the zero-water-point areas to be in cluster 0. To do so, we will adjust the columns of <code>zerowp</code> to match with <code>nigeria_spatiacluster</code>, transform it to the projected coordinate system of EPSG 26391, then stack the two table together.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>zerowpl <span class="ot">&lt;-</span> zerowp[, <span class="sc">-</span><span class="fu">c</span>(<span class="dv">2</span><span class="sc">:</span><span class="dv">5</span>)] <span class="sc">%&gt;%</span> </span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">CLUSTER =</span> <span class="st">"0"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">SP_CLUSTER =</span> <span class="st">"0"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb84-4"><a href="#cb84-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">relocate</span>(geometry, <span class="at">.after =</span> SP_CLUSTER) <span class="sc">%&gt;%</span> </span>
<span id="cb84-5"><a href="#cb84-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="st">"pct_functional"</span> <span class="ot">=</span> <span class="st">"hand"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb84-6"><a href="#cb84-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="st">"pct_nonfunctional"</span> <span class="ot">=</span> <span class="st">"mechanized"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb84-7"><a href="#cb84-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="st">"pct_hand"</span> <span class="ot">=</span> <span class="st">"greater_300_cap"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb84-8"><a href="#cb84-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="st">"pct_greater300"</span> <span class="ot">=</span> <span class="st">"less_300_cap"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb84-9"><a href="#cb84-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="st">"pct_rural"</span> <span class="ot">=</span> <span class="st">"rural"</span>)</span>
<span id="cb84-10"><a href="#cb84-10" aria-hidden="true" tabindex="-1"></a>zerowpl <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(zerowpl, <span class="at">crs =</span> <span class="dv">26391</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Now we will use <code>rbind()</code> of Base R to stack <code>nigeria_spatialcluster</code> and <code>zerowpl</code> together to create a data table of 9 clusters.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>skater_map <span class="ot">&lt;-</span> <span class="fu">rbind</span>(nigeria_spatialcluster, zerowpl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Now we can map the clusters created by SKATER method. Notice that cluster 0 is not a “true cluster” for analysis. It is added in for visualization only and we will not analyze its content.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>skater_clust <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(skater_map) <span class="sc">+</span> </span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">"SP_CLUSTER"</span>,</span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"SKATER Clusters"</span>) <span class="sc">+</span></span>
<span id="cb86-4"><a href="#cb86-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"SKATER Cluster Map"</span>,</span>
<span id="cb86-5"><a href="#cb86-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.position =</span> <span class="st">"center"</span>,</span>
<span id="cb86-6"><a href="#cb86-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="fl">1.4</span>,</span>
<span id="cb86-7"><a href="#cb86-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.height =</span> <span class="fl">0.25</span>,</span>
<span id="cb86-8"><a href="#cb86-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.width =</span> <span class="fl">0.3</span>,</span>
<span id="cb86-9"><a href="#cb86-9" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.position =</span> <span class="fu">c</span>(<span class="st">"right"</span>, <span class="st">"bottom"</span>),</span>
<span id="cb86-10"><a href="#cb86-10" aria-hidden="true" tabindex="-1"></a>            <span class="at">frame =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb86-11"><a href="#cb86-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>)</span>
<span id="cb86-12"><a href="#cb86-12" aria-hidden="true" tabindex="-1"></a>skater_clust</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Take-home_Ex2_files/figure-html/unnamed-chunk-61-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="spatially-constrained-clustering-glustgeo-method" class="level2">
<h2 class="anchored" data-anchor-id="spatially-constrained-clustering-glustgeo-method">Spatially Constrained Clustering: GlustGeo Method</h2>
<p>ClustGeo method is a Ward-like hierarchical clustering method. It fins the balance between the similarity of the variables and the contiguity of the observations. In R, ClustGeo is done using the functions of the <strong>ClustGeo</strong> package. In the code chunk below, we will use <code>hclustgeo()</code> to compute the dissimilarity matrix.</p>
<p>The balance is represented by a value of alpha. We need to find the right balance to increase the spatial contiguity without reducing the quality of the non-spatial clustering. To do that, we can use <code>choicealpha()</code>.</p>
<p>Before we can performed spatially constrained hierarchical clustering, a spatial distance matrix will be derived by using <code>st_distance()</code> of sf package.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a>dist <span class="ot">&lt;-</span> <span class="fu">st_distance</span>(nga_wp, nga_wp)</span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a>distmat <span class="ot">&lt;-</span> <span class="fu">as.dist</span>(dist)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>We will use <code>choicealpha()</code> to compute the value for mixing parameter alpha.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a>cr <span class="ot">&lt;-</span> <span class="fu">choicealpha</span>(proxmat, distmat, <span class="at">range.alpha =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="fl">0.1</span>), <span class="at">K=</span><span class="dv">8</span>, <span class="at">graph =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Take-home_Ex2_files/figure-html/unnamed-chunk-63-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="Take-home_Ex2_files/figure-html/unnamed-chunk-63-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Based on the graph, alpha equal 0.3 is chosen.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a>clustG <span class="ot">&lt;-</span> <span class="fu">hclustgeo</span>(proxmat, distmat, <span class="at">alpha =</span> <span class="fl">0.3</span>)</span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a>groups <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(<span class="fu">cutree</span>(clustG, <span class="at">k=</span><span class="dv">8</span>))</span>
<span id="cb89-3"><a href="#cb89-3" aria-hidden="true" tabindex="-1"></a>nigeria_Gcluster <span class="ot">&lt;-</span> <span class="fu">cbind</span>(nga_wp, <span class="fu">as.matrix</span>(groups)) <span class="sc">%&gt;%</span></span>
<span id="cb89-4"><a href="#cb89-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="st">`</span><span class="at">GEOCLUSTER</span><span class="st">`</span> <span class="ot">=</span> <span class="st">`</span><span class="at">as.matrix.groups.</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Like with SKATER, now we combine the data of zero-water-point areas to display on the map together with the ClustGeo clusters.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a>zewpgeo <span class="ot">&lt;-</span> zerowpl[,<span class="sc">-</span><span class="fu">c</span>(<span class="dv">10</span>)] <span class="sc">%&gt;%</span> </span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="st">"GEOCLUSTER"</span> <span class="ot">=</span> <span class="st">"SP_CLUSTER"</span>)</span>
<span id="cb90-3"><a href="#cb90-3" aria-hidden="true" tabindex="-1"></a>geo_map <span class="ot">&lt;-</span> <span class="fu">rbind</span>(nigeria_Gcluster, zewpgeo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Now we can map the spatially-constraned ClustGeo clusters.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a>geo_clust <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(geo_map) <span class="sc">+</span> </span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">"GEOCLUSTER"</span>,</span>
<span id="cb91-3"><a href="#cb91-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"ClustGeo Clusters"</span>) <span class="sc">+</span></span>
<span id="cb91-4"><a href="#cb91-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"ClustGeo Cluster Map"</span>,</span>
<span id="cb91-5"><a href="#cb91-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.position =</span> <span class="st">"center"</span>,</span>
<span id="cb91-6"><a href="#cb91-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="fl">1.4</span>,</span>
<span id="cb91-7"><a href="#cb91-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.height =</span> <span class="fl">0.25</span>,</span>
<span id="cb91-8"><a href="#cb91-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.width =</span> <span class="fl">0.3</span>,</span>
<span id="cb91-9"><a href="#cb91-9" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.position =</span> <span class="fu">c</span>(<span class="st">"right"</span>, <span class="st">"bottom"</span>),</span>
<span id="cb91-10"><a href="#cb91-10" aria-hidden="true" tabindex="-1"></a>            <span class="at">frame =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb91-11"><a href="#cb91-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>)</span>
<span id="cb91-12"><a href="#cb91-12" aria-hidden="true" tabindex="-1"></a>geo_clust</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Take-home_Ex2_files/figure-html/unnamed-chunk-66-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="comparing-two-clustering-methods" class="level2">
<h2 class="anchored" data-anchor-id="comparing-two-clustering-methods">Comparing two clustering methods</h2>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(skater_clust, geo_clust, <span class="at">asp =</span> <span class="dv">1</span>, <span class="at">ncol =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Take-home_Ex2_files/figure-html/unnamed-chunk-67-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>By comparing the map visualization, we can see that SKATER produces a cleaner view of regionalization, with the LGAs packed neatly together. ClustGeo, on the other hand, also produces regions that relatively overlap with the regions produced by SKATER, but some areas are scattering far from the main clustered region, and the border of the clustered region is not clear.</p>
<p>In addition, Cluster 1, 4, 6 contain very small LGAs that lie far away from each other. This will hinder customized efforts to organize water supply improvement initiatives. We can see that ClustGeo is not the appropriate tool to aid policy makers.</p>
<p>For this reason, we will base our next analysis on the SKATER method.</p>
</section>
<section id="multivariate-visualization-of-skater-clusters" class="level2">
<h2 class="anchored" data-anchor-id="multivariate-visualization-of-skater-clusters">Multivariate visualization of SKATER clusters</h2>
<p>To compare the clusters, we will display their variable ranges in the form of boxplots. When put next to each other, this visualization method proves effective to compare the difference of the clusters. To do this task, we will use <code>ggparcoord()</code> from <strong>GGally</strong> package.</p>
<p>First, we will load the <strong>GGally</strong> package.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(GGally)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>The graphs are drawn with the code below.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggparcoord</span>(<span class="at">data =</span> nigeria_spatialcluster, </span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a>           <span class="at">columns =</span> <span class="fu">c</span>(<span class="dv">3</span><span class="sc">:</span><span class="dv">9</span>), </span>
<span id="cb94-3"><a href="#cb94-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">scale =</span> <span class="st">"globalminmax"</span>,</span>
<span id="cb94-4"><a href="#cb94-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">alphaLines =</span> <span class="fl">0.2</span>,</span>
<span id="cb94-5"><a href="#cb94-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">boxplot =</span> <span class="cn">TRUE</span>, </span>
<span id="cb94-6"><a href="#cb94-6" aria-hidden="true" tabindex="-1"></a>           <span class="at">title =</span> <span class="st">"Plots of SKATER Cluster Variables"</span>) <span class="sc">+</span></span>
<span id="cb94-7"><a href="#cb94-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(<span class="at">rows =</span> <span class="fu">vars</span>(SP_CLUSTER)) <span class="sc">+</span> </span>
<span id="cb94-8"><a href="#cb94-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">10</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Take-home_Ex2_files/figure-html/fig%204-1.png" class="img-fluid" width="480"></p>
</div>
</div>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a>nigeria_spatialcluster <span class="sc">%&gt;%</span> </span>
<span id="cb95-2"><a href="#cb95-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_set_geometry</span>(<span class="cn">NULL</span>) <span class="sc">%&gt;%</span></span>
<span id="cb95-3"><a href="#cb95-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(SP_CLUSTER) <span class="sc">%&gt;%</span></span>
<span id="cb95-4"><a href="#cb95-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">functional =</span> <span class="fu">mean</span>(functional),</span>
<span id="cb95-5"><a href="#cb95-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">nonfunctional =</span> <span class="fu">mean</span>(nonfunctional),</span>
<span id="cb95-6"><a href="#cb95-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">pfunc =</span> <span class="fu">mean</span>(pct_functional),</span>
<span id="cb95-7"><a href="#cb95-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">pnfunc =</span> <span class="fu">mean</span>(pct_nonfunctional),</span>
<span id="cb95-8"><a href="#cb95-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">phand =</span> <span class="fu">mean</span>(pct_hand),</span>
<span id="cb95-9"><a href="#cb95-9" aria-hidden="true" tabindex="-1"></a>            <span class="at">pg300 =</span> <span class="fu">mean</span>(pct_greater300),</span>
<span id="cb95-10"><a href="#cb95-10" aria-hidden="true" tabindex="-1"></a>            <span class="at">prural =</span> <span class="fu">mean</span>(pct_rural))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 8
  SP_CLUSTER functional nonfunctional pfunc pnfunc phand pg300 prural
  &lt;fct&gt;           &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
1 1               10.7          73.0   37.7   40.0  61.1  16.7   90.6
2 2                2.37         22.6   37.3   44.3  16.7  63.8   71.5
3 3               21.1          46.4   75.5   24.4  86.4  13.2   83.5
4 4                4.50         22.5   47.0   23.7  12.0  57.8   31.6
5 5                9.99         85.3   42.1   46.9  55.2  33.0   78.0
6 6                2.19          4.33  71.6   28.4  64.6  34.9   73.0
7 7                8.78         52.6   51.4   41.3  57.5  34.9   70.8
8 8                4.77          8.08  55.1   11.9  42.3  57.4   63.2</code></pre>
</div>
</div>
<ul>
<li><p><strong>Cluster 1:</strong> is the region in the south east of Nigeria. It contains the highest percentage of rural water points and a second-highest number of non-functional water point count. Water point capacity is low and mostly manual with hand pump. The region also contains the lower outliers of rural water point percentage, suggesting the presence of cities.</p></li>
<li><p><strong>Cluster 2:</strong> lies in the south of Nigeria. This region has more than 71.5% of rural water points, but the percentage of water points with above-median capacity is also high (63.8%). The values of water point count and water point percentage suggests that the total water point count of this region is relatively low. The percentage of non-functional water points here is the second-highest.</p></li>
<li><p><strong>Cluster 3:</strong> spans from the north to the central of Nigeria. This region is characterized with the highest number of functional water points. The percentage of hand pump water point is also the highest among the clusters with the lowest average capacity. While the percentage of non-functional water points are the second-lowest, the water points in this region are not efficient due to manual process and low capacity.</p></li>
<li><p><strong>Cluster 4:</strong> is in the south east of Nigeria and contains the largest city of the nation - Lagos. The urban nature of the region is reflected by its low percentage of rural water points, with the highest average percentage of above-median capacity water points. The water points in the region is also highly mechanized, with the lowest percentage of hand pump water points.</p></li>
<li><p><strong>Cluster 5:</strong> lies in the central east of Nigeria. It has the highest average count of non-functional water points. The percentage of non-functional water points is also the highest among all clusters.</p></li>
<li><p><strong>Cluster 6:</strong> is located in the far west of Nigeria. The number of water points is low. While the region has a high percentage of functional water points, it can because of the low water point count. This is another region of rural areas with manual and low capacity water points.</p></li>
<li><p><strong>Cluster 7:</strong> is in the north west of Nigeria. This region has high value of non-functional water point count, and low value of functional water point count. The average percentage of functional and non-functional water points are roughly equal, suggesting some areas having low count of total water points. The majority of the water point in this region lies in the rural area. This area also contains the second-lowest percentage of water points with higher-than-median capacity.</p></li>
<li><p><strong>Cluster 8:</strong> is in the north east of Nigeria. Based on the choropleth map of total water point count in the EDA step, we can see that this part of Nigeria has the lowest water point count, and some LGAs (excluded from the cluster) do not have any water point at all. This is reflected in the low functional and non-functional water point count, yet high functional water point percentage.</p></li>
</ul>
</section>
<section id="conclusion-and-improvement" class="level2">
<h2 class="anchored" data-anchor-id="conclusion-and-improvement">Conclusion and Improvement</h2>
<p>With the spatially constrained clustering method, we can regionalize the LGAs in Nigeria based on the characteristic of water points in each region and how the LGAs are linked to each other. This method can be a useful tool to categorize and visualize regions for policy makers when it comes to improving the water supply in Nigeria.</p>
<p>This analysis can be improved even more. When looking at the water point count, we can’t help but questioning: why do some areas have less water points than others, and why some have more non-functional water points than others? Many factors can contribute to water point count and water point functionality, like population distribution, the economic health of the region, its geography and natural water supply, even the climate of the region. That information is not included in our analysis, but it can help us in producing more meaningful regionalization.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>