<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.189">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Sylvia’s Geospatial Journey - Take-home Exercise 1: How Functional are the Water Points in Nigeria?</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Sylvia’s Geospatial Journey</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercises" role="button" data-bs-toggle="dropdown" aria-expanded="false">Hands-on Exercises</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercises">    
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex01.html">
 <span class="dropdown-text">Hands-on Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex02.html">
 <span class="dropdown-text">Hands-on Exercise 2</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-in-class-exercises" role="button" data-bs-toggle="dropdown" aria-expanded="false">In-class Exercises</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-in-class-exercises">    
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex1/In-class_ex1.html">
 <span class="dropdown-text">In-class Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex2/In-class_Ex2.html">
 <span class="dropdown-text">In-class Exercise 2</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercises" role="button" data-bs-toggle="dropdown" aria-expanded="false">Take-home Exercises</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-take-home-exercises">    
        <li>
    <a class="dropdown-item" href="../../Take-home_Ex/Take-home_Ex1/Take-home_Ex1.html">
 <span class="dropdown-text">Take-home Exercise 1</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html">Home</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html">About</a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">Overview</a>
  <ul class="collapse">
  <li><a href="#social-context" id="toc-social-context" class="nav-link" data-scroll-target="#social-context">Social Context</a></li>
  <li><a href="#objective" id="toc-objective" class="nav-link" data-scroll-target="#objective">Objective</a></li>
  </ul></li>
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup">Setup</a>
  <ul class="collapse">
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">Data</a></li>
  <li><a href="#r-packages-used" id="toc-r-packages-used" class="nav-link" data-scroll-target="#r-packages-used">R Packages Used</a></li>
  </ul></li>
  <li><a href="#importing-data" id="toc-importing-data" class="nav-link" data-scroll-target="#importing-data">Importing Data</a>
  <ul class="collapse">
  <li><a href="#importing-nigeria-water-point-geospatial-data" id="toc-importing-nigeria-water-point-geospatial-data" class="nav-link" data-scroll-target="#importing-nigeria-water-point-geospatial-data">Importing Nigeria water point geospatial data</a></li>
  <li><a href="#importing-nigeria-adm2-aspatial-data" id="toc-importing-nigeria-adm2-aspatial-data" class="nav-link" data-scroll-target="#importing-nigeria-adm2-aspatial-data">Importing Nigeria ADM2 aspatial data</a></li>
  </ul></li>
  <li><a href="#exploratory-data-analysis-and-data-wrangling" id="toc-exploratory-data-analysis-and-data-wrangling" class="nav-link" data-scroll-target="#exploratory-data-analysis-and-data-wrangling">Exploratory Data Analysis and Data Wrangling</a>
  <ul class="collapse">
  <li><a href="#wp-geospatial-data" id="toc-wp-geospatial-data" class="nav-link" data-scroll-target="#wp-geospatial-data"><code>wp</code> geospatial data</a></li>
  <li><a href="#nga-aspatial-data" id="toc-nga-aspatial-data" class="nav-link" data-scroll-target="#nga-aspatial-data"><code>nga</code> aspatial data</a></li>
  <li><a href="#performing-point-in-polygon-count" id="toc-performing-point-in-polygon-count" class="nav-link" data-scroll-target="#performing-point-in-polygon-count">Performing Point-in-Polygon Count</a></li>
  <li><a href="#saving-the-analytical-data-table" id="toc-saving-the-analytical-data-table" class="nav-link" data-scroll-target="#saving-the-analytical-data-table">Saving the analytical data table</a></li>
  </ul></li>
  <li><a href="#visualizing-the-data" id="toc-visualizing-the-data" class="nav-link" data-scroll-target="#visualizing-the-data">Visualizing the Data</a>
  <ul class="collapse">
  <li><a href="#displaying-non-functional-water-points-with-choropleth-map" id="toc-displaying-non-functional-water-points-with-choropleth-map" class="nav-link" data-scroll-target="#displaying-non-functional-water-points-with-choropleth-map">Displaying non-functional water points with choropleth map</a></li>
  </ul></li>
  <li><a href="#global-spatial-autocorrelation" id="toc-global-spatial-autocorrelation" class="nav-link" data-scroll-target="#global-spatial-autocorrelation">Global Spatial Autocorrelation</a>
  <ul class="collapse">
  <li><a href="#computing-spatial-weights" id="toc-computing-spatial-weights" class="nav-link" data-scroll-target="#computing-spatial-weights">Computing Spatial Weights</a></li>
  <li><a href="#global-spatial-autocorrelation-morans-i" id="toc-global-spatial-autocorrelation-morans-i" class="nav-link" data-scroll-target="#global-spatial-autocorrelation-morans-i">Global Spatial Autocorrelation: Moran’s I</a></li>
  <li><a href="#global-spatial-autocorrelation-gearys-c" id="toc-global-spatial-autocorrelation-gearys-c" class="nav-link" data-scroll-target="#global-spatial-autocorrelation-gearys-c">Global Spatial Autocorrelation: Geary’s C</a></li>
  </ul></li>
  <li><a href="#spatial-correlogram-with-morans-i" id="toc-spatial-correlogram-with-morans-i" class="nav-link" data-scroll-target="#spatial-correlogram-with-morans-i">Spatial Correlogram with Moran’s I</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Take-home Exercise 1: How Functional are the Water Points in Nigeria?</h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview">Overview</h2>
<section id="social-context" class="level3">
<h3 class="anchored" data-anchor-id="social-context">Social Context</h3>
<p>Water is a critical asset of all communities and nations. It is the core neccessity to sustain the life of both humans and livestock. Lack of access to potable water can lead to serious health hazards and even conflicts between communities and states. According to a 2022 report by World Bank, about 70 million Nigerians do not have access to drinkable water. Access to piped water has decreased from 39% in 1990 to only 11% in 2021. This phenomenon contributes to a surge in violence in Nigeria when communities Fulani herders ad farmers fight over water supplies.</p>
<p>Why is there a water crisis in Nigeria? To gain a perspective on the answer, we will examine the quality and distribution of water supply points in Nigeria.</p>
</section>
<section id="objective" class="level3">
<h3 class="anchored" data-anchor-id="objective">Objective</h3>
<p>The objective of this exercise is to apply appropriate global and local measures of spatial association techniques to reveals the spatial patterns of non-functional water points in Nigeria.</p>
</section>
</section>
<section id="setup" class="level2">
<h2 class="anchored" data-anchor-id="setup">Setup</h2>
<section id="data" class="level3">
<h3 class="anchored" data-anchor-id="data">Data</h3>
<section id="aspatial-data" class="level4">
<h4 class="anchored" data-anchor-id="aspatial-data">Aspatial Data</h4>
<p>The aspatial data of water points quality, status and other relevant information is taken from <a href="https://data.waterpointdata.org/dataset/Water-Point-Data-Exchange-Plus-WPdx-/eqje-vguj/data">WPdx Global Data Repositories - WPdx+ version</a>. The data set is downloaded in Shapefile format.</p>
</section>
<section id="geospatial-data" class="level4">
<h4 class="anchored" data-anchor-id="geospatial-data">Geospatial Data</h4>
<p>The geospatial data of Nigeria administrative regions is downloaded from <a href="https://www.geoboundaries.org/index.html#getdata">Geoboundaries</a>. The data level of ADM2, published in 2020, will be used.</p>
</section>
</section>
<section id="r-packages-used" class="level3">
<h3 class="anchored" data-anchor-id="r-packages-used">R Packages Used</h3>
<ul>
<li><p><strong>sf</strong>: used for importing, managing, and processing geospatial data</p></li>
<li><p><strong>tidyverse</strong>: a collection of packages for data science tasks. It contains the sub-packages dplyr, ggplot2, forcats, tibble, readr, stringr, tidyr, purrr</p></li>
<li><p><strong>tmap</strong>: used for creating thematic maps, such as choropleth and bubble maps</p></li>
<li><p><strong>spdep</strong>: used for calculating spatial dependence - weighting schemes and statistics</p></li>
<li><p><strong>funModeling</strong>: used for EDA and data preparation</p></li>
</ul>
<p>We load the packages into our working environment using the code below.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(sf, tidyverse, tmap, spdep, funModeling)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
</section>
<section id="importing-data" class="level2">
<h2 class="anchored" data-anchor-id="importing-data">Importing Data</h2>
<section id="importing-nigeria-water-point-geospatial-data" class="level3">
<h3 class="anchored" data-anchor-id="importing-nigeria-water-point-geospatial-data">Importing Nigeria water point geospatial data</h3>
<p>The data from WPdx Global Data Repositories comes in four files in dbf, prj, shp, shx formats. The files are renamed into <code>geo_export</code> for a more convenient reference.</p>
<p>Using <code>st_read()</code> from the <strong>sf</strong> package, we import the aspatial data into our working environment. The data is imported as a simple feature data table.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>wp <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"data"</span>, <span class="at">layer =</span> <span class="st">"geo_export"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="importing-nigeria-adm2-aspatial-data" class="level3">
<h3 class="anchored" data-anchor-id="importing-nigeria-adm2-aspatial-data">Importing Nigeria ADM2 aspatial data</h3>
<p>The data from Geoboundaries comes in six files in dbf, geojson, prj, shp, shx, topojson formats. The files are renamed to <code>NGA-ADM2</code> for easier reference. To import these files as a simple feature data table, we also use <code>st_read().</code></p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>nga <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"data"</span>, <span class="at">layer =</span> <span class="st">"NGA-ADM2"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
</section>
<section id="exploratory-data-analysis-and-data-wrangling" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-data-analysis-and-data-wrangling">Exploratory Data Analysis and Data Wrangling</h2>
<p>The goals of this step include:</p>
<ul>
<li><p>Examine the data structure and format, ensure consistent format between geospatial and aspatial data.</p></li>
<li><p>Study the content of the data tables and filter out data that are not related to water points in Nigeria.</p></li>
<li><p>Explore data type and data validity relating to the functionality of water points in Nigeria, transform the data where necessary.</p></li>
</ul>
<section id="wp-geospatial-data" class="level3">
<h3 class="anchored" data-anchor-id="wp-geospatial-data"><code>wp</code> geospatial data</h3>
<section id="checking-the-crs-of-geospatial-data" class="level4">
<h4 class="anchored" data-anchor-id="checking-the-crs-of-geospatial-data">Checking the CRS of geospatial data</h4>
<p>First, we use <code>st_geometry()</code> to check the geometry list column of <code>wp</code>. There are 406,566 observations under the WGS84 coordinate reference system (CRS). Let’s take notes that the geometry type is <code>point</code> 🔑</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_geometry</span>(wp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Since the shapefile is in WGS84 CRS, we will assign <code>crs = 4326</code> to <code>wp</code>. 4326 is the code of WGS84 in EPSG code. The task is conducted using <code>st_set_crs()</code>.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>wp <span class="ot">&lt;-</span> <span class="fu">st_set_crs</span>(wp, <span class="dv">4326</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="filtering-relevant-information" class="level4">
<h4 class="anchored" data-anchor-id="filtering-relevant-information">Filtering relevant information</h4>
<p>Next, we will examine the attributes in the data table using <code>glimpse()</code> from <strong>dplyr</strong>.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(wp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>We notice that in the <code>clean_coun</code> column, there are many countries name such as Malawi, Ghana, Sierra Leone, etc. This means that the <code>wp</code> data set contains the information of other countries besides Nigeria. <code>filter()</code> of the package <strong>dplyr</strong> is used to get the data that only belongs to Nigeria.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>wp <span class="ot">&lt;-</span> wp <span class="sc">%&gt;%</span> <span class="fu">filter</span>(clean_coun <span class="sc">==</span> <span class="st">"Nigeria"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Now we will examine the filtered <code>wp</code> data set using <code>head()</code> of Base R. The function reveals that <code>wp</code> now only contains Nigeria-relevant data.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(wp, <span class="at">n =</span> <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Now we will write the filtered data table into a new <code>rds</code> file named <code>wp_nga</code> using the <code>write_rds()</code> function from the <strong>sf</strong> package.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(wp, <span class="st">"data/wp_nga.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>From this point on, we will work on the <code>wp_nga</code> file.</p>
</section>
<section id="exploring-the-water-point-status-data" class="level4">
<h4 class="anchored" data-anchor-id="exploring-the-water-point-status-data">Exploring the water point status data</h4>
<p>From the result of the code above, we notice that column <code>status_cle</code> has NA values. Since our goal is to examine the functionality of the water points, the data in <code>status_cle</code> should be transformed to remove the NA values. One way to do it is to recode the NA values to “Unknown”. <code>replace_na()</code> from the <strong>tidyr</strong> package is used to do the mentioned task.</p>
<p>To preserve the existing variables while adding new ones, <code>mutate()</code> from the <strong>dplyr</strong> package is used.</p>
<p>All changes are written into the <code>wp_nga</code> file using <code>read_rds()</code>.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>wp_nga <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/wp_nga.rds"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">status_cle =</span> <span class="fu">replace_na</span>(status_cle, <span class="st">"Unknown"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Let’s look at the distribution of <code>status_cle</code>. We will use <code>freq()</code> from the <strong>funModeling</strong> package for this task.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">freq</span>(<span class="at">data=</span>wp_nga, </span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">input =</span> <span class="st">'status_cle'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>We can see that there are two variables that carry the same meaning: <em>Non-Functional due to dry season</em> and <em>Non functional due to dry season</em>. We will use <code>replace()</code> from <strong>dplyr</strong> to do this task.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>wp_nga <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/wp_nga.rds"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">status_cle =</span> <span class="fu">replace</span>(status_cle, status_cle <span class="sc">==</span> <span class="st">"Non functional due to dry season"</span>, <span class="st">"Non-Functional due to dry season"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">status_cle =</span> <span class="fu">replace_na</span>(status_cle, <span class="st">"Unknown"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Let’s re-examine the distribution of <code>status_cle</code>.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">freq</span>(<span class="at">data=</span>wp_nga, </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">input =</span> <span class="st">'status_cle'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="extracting-non-functional-water-point-data" class="level4">
<h4 class="anchored" data-anchor-id="extracting-non-functional-water-point-data">Extracting non-functional water point data</h4>
<p>Non-functional water points are defined as those which are not functional or abandoned. Using <code>filter()</code> from the dplyr package, we will save the non-functional water point data into a simple feature data table named <code>wpt_nonfunctional</code>.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>wpt_nonfunctional <span class="ot">&lt;-</span> wp_nga <span class="sc">%&gt;%</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(status_cle <span class="sc">%in%</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>           <span class="fu">c</span>(<span class="st">"Abandoned/Decommissioned"</span>, </span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>             <span class="st">"Abandoned"</span>,</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>             <span class="st">"Non-Functional"</span>,</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>             <span class="st">"Non-Functional due to dry season"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Now we can inspect the distribution of non-functional water points by type using <code>freq()</code>.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">freq</span>(<span class="at">data =</span> wpt_nonfunctional, <span class="at">input =</span> <span class="st">"status_cle"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
</section>
<section id="nga-aspatial-data" class="level3">
<h3 class="anchored" data-anchor-id="nga-aspatial-data"><code>nga</code> aspatial data</h3>
<section id="checking-the-crs-of-aspatial-data" class="level4">
<h4 class="anchored" data-anchor-id="checking-the-crs-of-aspatial-data">Checking the CRS of aspatial data</h4>
<p>We will check the CRS of <code>nga</code> using <code>st_geometry()</code>.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_geometry</span>(nga)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>As the CRS of <code>nga</code> is WGS84, we will assign <code>crs = 4326</code> using <code>st_set_crs()</code>.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>nga <span class="ot">&lt;-</span> <span class="fu">st_set_crs</span>(nga, <span class="dv">4326</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Next, we plot the geometry using <code>plot()</code> of Base R. As our data is the regions of Nigeria by administrative division management level 2, the map below depicts the <a href="https://en.wikipedia.org/wiki/Local_government_areas_of_Nigeria">774 Local Government Areas of Nigeria</a>.</p>
<p>From the map, it is noticeable that the size of government areas varies significantly. Let’s keep this in mind for further analysis 💪</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">st_geometry</span>(nga))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
</section>
<section id="performing-point-in-polygon-count" class="level3">
<h3 class="anchored" data-anchor-id="performing-point-in-polygon-count">Performing Point-in-Polygon Count</h3>
<p>Because the geometry type of our geospatial data is <code>point</code>, we need to compute the number of points inside each polygon. The functions below will be used for that task.</p>
<ul>
<li><p><code>mutate()</code>: preserves the existing variables while adding new variables, from <strong>dplyr</strong> package</p></li>
<li><p><code>st_intersects()</code>: spatial intersect predicate for stars and sfc object, from <strong>stars</strong> package, a sub-package of <strong>tmap</strong>.</p></li>
<li><p><code>lengths()</code>: get the length of each element of a list or atomic vector as an integer or numeric vector, from Base R.</p></li>
</ul>
<p>After the aggregation, the output will in in polygon geometry shape.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>nga_wp <span class="ot">&lt;-</span> nga <span class="sc">%&gt;%</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">`</span><span class="at">total wpt</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">lengths</span>(</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">st_intersects</span>(nga, wp_nga))) <span class="sc">%&gt;%</span> </span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">`</span><span class="at">wpt non-functional</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">lengths</span>(</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">st_intersects</span>(nga, wpt_nonfunctional)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="saving-the-analytical-data-table" class="level3">
<h3 class="anchored" data-anchor-id="saving-the-analytical-data-table">Saving the analytical data table</h3>
<p>Before saving the data table, we will compute the percentage of non-functional water points over the total number of water points in Nigeria.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>nga_wp <span class="ot">&lt;-</span> nga_wp <span class="sc">%&gt;%</span> </span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">`</span><span class="at">pct_non-functional</span><span class="st">`</span> <span class="ot">=</span> <span class="st">`</span><span class="at">wpt non-functional</span><span class="st">`</span><span class="sc">/</span><span class="st">`</span><span class="at">total wpt</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Now, we will save the sf data table <code>nga_wp</code> into a new rds file.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(nga_wp, <span class="st">"data/nga_wp.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
</section>
<section id="visualizing-the-data" class="level2">
<h2 class="anchored" data-anchor-id="visualizing-the-data">Visualizing the Data</h2>
<p>First, let’s reload the <code>nga_wp.rds</code> file into our working environment.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>nga_wp <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"data/nga_wp.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="displaying-non-functional-water-points-with-choropleth-map" class="level3">
<h3 class="anchored" data-anchor-id="displaying-non-functional-water-points-with-choropleth-map">Displaying non-functional water points with choropleth map</h3>
<p>To create the plots, we will use the <code>tm_shape()</code> and <code>tm_fill()</code> functions from <strong>tmap</strong> package. In addition, <code>tm_borders()</code> and <code>tm_layout()</code> will be used to customize the style of the map. Below are the functionality of the functions.</p>
<ul>
<li><p><code>tm_shape</code>: creates a tmap element that specifies the spatial data object.</p></li>
<li><p><code>tm_fill</code>: creates a tmap element that draws the polygons.</p></li>
<li><p><code>tm_borders</code>: creates a tmap element that defines the border of the polygons.</p></li>
<li><p><code>tm_layout</code>: specifies the map layout</p></li>
</ul>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>wp_pretty <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(nga_wp) <span class="sc">+</span> </span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">"wpt non-functional"</span>,</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"Water Point Count"</span>) <span class="sc">+</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Pretty Classification"</span>,</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.position =</span> <span class="st">"center"</span>,</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="dv">2</span>,</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.height =</span> <span class="fl">0.25</span>,</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.width =</span> <span class="fl">0.3</span>,</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.position =</span> <span class="fu">c</span>(<span class="st">"right"</span>, <span class="st">"bottom"</span>),</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>            <span class="at">frame =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>)</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>wp_quantile <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(nga_wp) <span class="sc">+</span> </span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">"wpt non-functional"</span>,</span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"Water Point Count"</span>,</span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>          <span class="at">style =</span> <span class="st">"quantile"</span>) <span class="sc">+</span></span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Quantile Classification"</span>,</span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.position =</span> <span class="st">"center"</span>,</span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="dv">2</span>,</span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.height =</span> <span class="fl">0.25</span>,</span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.width =</span> <span class="fl">0.3</span>,</span>
<span id="cb23-22"><a href="#cb23-22" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.position =</span> <span class="fu">c</span>(<span class="st">"right"</span>, <span class="st">"bottom"</span>),</span>
<span id="cb23-23"><a href="#cb23-23" aria-hidden="true" tabindex="-1"></a>            <span class="at">frame =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb23-24"><a href="#cb23-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>)</span>
<span id="cb23-25"><a href="#cb23-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-26"><a href="#cb23-26" aria-hidden="true" tabindex="-1"></a>wp_equal <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(nga_wp) <span class="sc">+</span> </span>
<span id="cb23-27"><a href="#cb23-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">"wpt non-functional"</span>,</span>
<span id="cb23-28"><a href="#cb23-28" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"Water Point Count"</span>,</span>
<span id="cb23-29"><a href="#cb23-29" aria-hidden="true" tabindex="-1"></a>          <span class="at">style =</span> <span class="st">"equal"</span>) <span class="sc">+</span></span>
<span id="cb23-30"><a href="#cb23-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Equal Classification"</span>,</span>
<span id="cb23-31"><a href="#cb23-31" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.position =</span> <span class="st">"center"</span>,</span>
<span id="cb23-32"><a href="#cb23-32" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="dv">2</span>,</span>
<span id="cb23-33"><a href="#cb23-33" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.height =</span> <span class="fl">0.25</span>,</span>
<span id="cb23-34"><a href="#cb23-34" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.width =</span> <span class="fl">0.3</span>,</span>
<span id="cb23-35"><a href="#cb23-35" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.position =</span> <span class="fu">c</span>(<span class="st">"right"</span>, <span class="st">"bottom"</span>),</span>
<span id="cb23-36"><a href="#cb23-36" aria-hidden="true" tabindex="-1"></a>            <span class="at">frame =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb23-37"><a href="#cb23-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>)</span>
<span id="cb23-38"><a href="#cb23-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-39"><a href="#cb23-39" aria-hidden="true" tabindex="-1"></a>wp_jenks <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(nga_wp) <span class="sc">+</span> </span>
<span id="cb23-40"><a href="#cb23-40" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">"wpt non-functional"</span>,</span>
<span id="cb23-41"><a href="#cb23-41" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"Water Point Count"</span>,</span>
<span id="cb23-42"><a href="#cb23-42" aria-hidden="true" tabindex="-1"></a>          <span class="at">style =</span> <span class="st">"jenks"</span>) <span class="sc">+</span></span>
<span id="cb23-43"><a href="#cb23-43" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Jenks Classification"</span>,</span>
<span id="cb23-44"><a href="#cb23-44" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.position =</span> <span class="st">"center"</span>,</span>
<span id="cb23-45"><a href="#cb23-45" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="dv">2</span>,</span>
<span id="cb23-46"><a href="#cb23-46" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.height =</span> <span class="fl">0.25</span>,</span>
<span id="cb23-47"><a href="#cb23-47" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.width =</span> <span class="fl">0.3</span>,</span>
<span id="cb23-48"><a href="#cb23-48" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.position =</span> <span class="fu">c</span>(<span class="st">"right"</span>, <span class="st">"bottom"</span>),</span>
<span id="cb23-49"><a href="#cb23-49" aria-hidden="true" tabindex="-1"></a>            <span class="at">frame =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb23-50"><a href="#cb23-50" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>wp_equal</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Take-home_Ex1_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>wp_pretty</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Take-home_Ex1_files/figure-html/unnamed-chunk-24-2.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>wp_jenks</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Take-home_Ex1_files/figure-html/unnamed-chunk-24-3.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>wp_quantile</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Take-home_Ex1_files/figure-html/unnamed-chunk-24-4.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>From the maps above, we can see that different interval classification produces different map views.</p>
<p><code>pretty</code> and <code>equal</code> methods divide the values into groups of equally-spaced values, so they can smooth out the distribution of non-functional water points.</p>
<p>The <code>Jenks</code> method produces well-balanced intervals. By definition, the Jenks method defines intervals so that they have the smallest in-class variance. This makes the Jenks method more suitable for high-variance data sets like <code>nga_wp</code>.</p>
<p>The <code>quantile</code> method produces a rather dire situation with a large area of land having the highest numbers of non-functional water points. However, the range of the highest quantile is relatively huge comparing to other quantiles, suggesting high variance data. We can say that the quantile method exaggerates the disfunctionality of water points in Nigeria due to outliers.</p>
<section id="displaying-data-distribution-with-histogram" class="level4">
<h4 class="anchored" data-anchor-id="displaying-data-distribution-with-histogram">Displaying data distribution with histogram</h4>
<p>To confirm the distribution of the data, we will use a histogram. From the histogram, it is clear that the data is highly skewed toward the right.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(nga_wp<span class="sc">$</span><span class="st">`</span><span class="at">wpt non-functional</span><span class="st">`</span>, <span class="at">xlab =</span> <span class="st">"Non-functional Water Point Count"</span>,</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Histogram of non-functional water points"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Take-home_Ex1_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
</section>
<section id="global-spatial-autocorrelation" class="level2">
<h2 class="anchored" data-anchor-id="global-spatial-autocorrelation">Global Spatial Autocorrelation</h2>
<p>Based on the maps above, we see that there are some areas with a higher number of non-functional water points than others. Is there a pattern for the distribution of the non-functional water points or do they just occur randomly? To answer that question, we will explore the global spatial autocorrelation of non-functional water points in Nigeria.</p>
<section id="computing-spatial-weights" class="level3">
<h3 class="anchored" data-anchor-id="computing-spatial-weights">Computing Spatial Weights</h3>
<p>Let’s consider four spatial weight methods.</p>
<ul>
<li><p><strong>Polygon Contiguity</strong>: this method defines the neighbor based on contiguity and is effective when the polygons are similar in size and distribution, and when spatial relationships are a function of polygon proximity. In this case, the size of the government areas of Nigeria have significantly varying sizes. Therefore, polygon contiguity is not a good fit.</p></li>
<li><p><strong>Fixed Distance</strong>: this method is effective for polygon data with large variation in polygon size (very large polygons at the edge of the study area, and very small polygons at the center of the study areas). On the map, we can see that Nigeria has very small government areas in the south, while bigger areas are scattered in the rest of the country, together with smaller areas in between. Therefore, the Fixed Distance method is not a good fit.</p></li>
<li><p><strong>Inverse Distance:</strong> this method is appropriate for with continuous data or to model the process where the closer the features are, the more likely they are going to interact/affect the other. The downside of this approach is that it considers every feature is potentially a neighbor of every other feature. Therefore, the method is computationally costly. Since our data set has up to 774 observations, this method is not appropriate considering the capability of our personal computer.</p></li>
<li><p><strong>Adaptive Distance (K Nearest Neighbor):</strong> this method is effective when the values associate with the features are skewed. Because our data is skewed to the right, this method is a good fit.</p></li>
</ul>
<section id="converting-data-into-projected-coordinate-system" class="level4">
<h4 class="anchored" data-anchor-id="converting-data-into-projected-coordinate-system">Converting data into projected coordinate system</h4>
<p>Because Adaptive Distance spatial weight method is distance-based spatial weight method, the data needs to be converted into projected coordinate system. The EPSG code we will convert the data into is <a href="https://epsg.io/26391">EPSG:26391</a>, used for Nigeria West Belt. We will use <code>st_transform()</code> from the <strong>sf</strong> package for the task.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>nga_wp <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(nga_wp, <span class="at">crs =</span> <span class="dv">26391</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="computing-adaptive-weight-matrix" class="level4">
<h4 class="anchored" data-anchor-id="computing-adaptive-weight-matrix">Computing Adaptive Weight Matrix</h4>
<p>As a rule of thumb, when computing adaptive weight matrix, we should ensure that each feature has at least 8 neighbors. To do the task, the functions below are called:</p>
<ul>
<li><p><a href="https://www.rdocumentation.org/packages/spdep/versions/1.2-7/topics/knn2nb"><code>knn2nb()</code></a>: converts a&nbsp;<strong>knn</strong>&nbsp;object returned by&nbsp;<strong>knearneigh</strong>&nbsp;into a neighbors list of class&nbsp;<strong>nb</strong>&nbsp;with a list of integer vectors containing neighbor region number ids.</p></li>
<li><p><a href="https://r-spatial.github.io/spdep/reference/knearneigh.html"><code>knearneigh()</code></a>: returns a matrix with the indices of points belonging to the set of the k nearest neighbours of each other.</p></li>
<li><p><a href="https://purrr.tidyverse.org/reference/map.html"><code>map_dbl()</code></a>: returns an atomic vector of the indicative type.</p></li>
<li><p><a href="https://r-spatial.github.io/sf/reference/geos_unary.html"><code>st_centroid()</code></a>: calculates and retrieve the centroid of the feature.</p></li>
<li><p><a href="https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/cbind"><code>cbind()</code></a>: merges two data frames/vectors/matrices together</p></li>
</ul>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Calculate the longitude and latitude</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>longitude <span class="ot">&lt;-</span> <span class="fu">map_dbl</span>(nga_wp<span class="sc">$</span>geometry, <span class="sc">~</span><span class="fu">st_centroid</span>(.x)[[<span class="dv">1</span>]])</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>latitude <span class="ot">&lt;-</span> <span class="fu">map_dbl</span>(nga_wp<span class="sc">$</span>geometry, <span class="sc">~</span><span class="fu">st_centroid</span>(.x)[[<span class="dv">2</span>]])</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>coords <span class="ot">&lt;-</span> <span class="fu">cbind</span>(longitude, latitude)</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>wp_k8 <span class="ot">&lt;-</span> <span class="fu">knn2nb</span>(<span class="fu">knearneigh</span>(coords, <span class="at">k =</span> <span class="dv">8</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Displaying the content of <code>wp_k8</code> matrix using <code>str()</code>. Each feature has 8 neighbors.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(wp_k8)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>List of 774
 $ : int [1:8] 2 321 364 548 597 624 721 725
 $ : int [1:8] 1 321 548 597 624 721 725 726
 $ : int [1:8] 241 250 261 447 492 507 509 526
 $ : int [1:8] 12 20 257 263 446 454 466 690
 $ : int [1:8] 203 208 286 288 331 334 539 738
 $ : int [1:8] 170 217 218 337 379 553 577 601
 $ : int [1:8] 8 176 214 281 283 306 544 555
 $ : int [1:8] 7 214 281 306 327 544 555 651
 $ : int [1:8] 18 19 218 337 574 576 601 757
 $ : int [1:8] 25 216 325 364 365 528 552 632
 $ : int [1:8] 26 27 43 68 191 524 565 762
 $ : int [1:8] 135 263 417 429 446 454 690 695
 $ : int [1:8] 31 37 211 320 393 570 583 584
 $ : int [1:8] 170 363 379 546 563 577 581 589
 $ : int [1:8] 22 49 82 177 297 306 580 623
 $ : int [1:8] 30 187 188 296 328 357 360 635
 $ : int [1:8] 35 275 295 378 460 591 638 639
 $ : int [1:8] 9 19 218 376 574 576 601 757
 $ : int [1:8] 9 18 56 103 376 574 576 601
 $ : int [1:8] 4 106 125 239 263 419 454 466
 $ : int [1:8] 60 61 162 269 520 578 596 626
 $ : int [1:8] 49 297 326 443 515 623 682 693
 $ : int [1:8] 54 291 292 536 537 614 618 619
 $ : int [1:8] 84 123 437 476 527 652 673 761
 $ : int [1:8] 10 181 216 314 325 366 552 730
 $ : int [1:8] 11 27 68 191 336 439 562 762
 $ : int [1:8] 11 26 191 439 562 565 663 762
 $ : int [1:8] 29 178 299 300 301 358 369 598
 $ : int [1:8] 172 173 178 182 358 378 460 591
 $ : int [1:8] 16 39 41 186 192 329 357 360
 $ : int [1:8] 13 37 211 289 561 570 583 584
 $ : int [1:8] 51 62 461 462 515 623 682 693
 $ : int [1:8] 47 166 227 238 242 655 743 750
 $ : int [1:8] 42 104 136 137 213 553 559 757
 $ : int [1:8] 17 275 276 277 278 279 295 460
 $ : int [1:8] 50 107 247 408 432 455 681 759
 $ : int [1:8] 38 40 211 212 570 583 584 629
 $ : int [1:8] 30 39 40 41 186 192 320 570
 $ : int [1:8] 30 38 40 41 186 192 320 329
 $ : int [1:8] 37 38 39 41 186 192 320 570
 $ : int [1:8] 30 38 39 40 186 192 360 634
 $ : int [1:8] 86 136 137 499 587 613 718 734
 $ : int [1:8] 11 68 157 524 549 565 590 645
 $ : int [1:8] 16 45 192 290 303 328 360 634
 $ : int [1:8] 44 187 290 303 328 341 360 599
 $ : int [1:8] 387 417 429 438 459 521 668 742
 $ : int [1:8] 33 111 166 234 238 691 698 750
 $ : int [1:8] 65 113 265 386 407 428 482 701
 $ : int [1:8] 22 32 297 326 515 623 682 693
 $ : int [1:8] 36 98 107 247 409 416 432 681
 $ : int [1:8] 32 62 461 462 515 580 623 693
 $ : int [1:8] 53 78 165 293 532 602 603 636
 $ : int [1:8] 52 78 80 165 280 602 621 636
 $ : int [1:8] 23 79 293 294 532 536 537 618
 $ : int [1:8] 122 169 246 333 430 571 605 697
 $ : int [1:8] 77 368 376 533 534 576 601 728
 $ : int [1:8] 53 58 199 312 322 323 621 622
 $ : int [1:8] 57 322 323 564 602 603 621 622
 $ : int [1:8] 88 128 129 259 493 700 714 748
 $ : int [1:8] 61 158 563 578 589 592 596 626
 $ : int [1:8] 21 60 269 578 589 592 596 626
 $ : int [1:8] 32 51 461 462 515 623 682 693
 $ : int [1:8] 90 237 384 416 467 497 765 772
 $ : int [1:8] 48 65 74 113 131 265 386 407
 $ : int [1:8] 48 64 74 113 265 407 683 701
 $ : int [1:8] 19 103 104 288 331 338 351 574
 $ : int [1:8] 347 348 560 566 567 609 640 694
 $ : int [1:8] 11 43 157 190 191 549 590 645
 $ : int [1:8] 140 146 248 274 473 500 512 513
 $ : int [1:8] 71 298 299 301 341 343 344 610
 $ : int [1:8] 70 172 173 298 299 343 344 625
 $ : int [1:8] 17 361 566 567 568 609 638 639
 $ : int [1:8] 72 361 374 377 404 607 665 666
 $ : int [1:8] 65 109 113 251 265 683 741 754
 $ : int [1:8] 110 272 398 422 433 485 501 768
 $ : int [1:8] 254 287 427 459 470 547 647 677
 $ : int [1:8] 56 195 533 534 579 618 619 728
 $ : int [1:8] 52 54 79 80 165 215 532 636
 $ : int [1:8] 54 78 165 293 532 579 618 636
 $ : int [1:8] 52 53 78 165 215 280 636 739
 $ : int [1:8] 99 145 227 233 426 483 689 760
 $ : int [1:8] 15 32 49 51 177 352 580 623
 $ : int [1:8] 132 258 383 414 433 529 767 768
 $ : int [1:8] 24 131 148 386 437 482 673 692
 $ : int [1:8] 105 156 267 394 654 675 707 712
 $ : int [1:8] 42 136 137 499 587 613 718 734
 $ : int [1:8] 149 151 221 226 399 410 486 657
 $ : int [1:8] 59 116 128 150 489 648 700 714
 $ : int [1:8] 260 408 463 542 674 676 681 759
 $ : int [1:8] 63 163 236 237 384 452 710 765
 $ : int [1:8] 160 271 388 406 473 475 492 525
 $ : int [1:8] 95 119 390 391 392 423 487 656
 $ : int [1:8] 73 354 374 402 594 607 665 666
 $ : int [1:8] 13 31 60 158 436 561 596 709
 $ : int [1:8] 92 390 391 392 405 423 469 656
 $ : int [1:8] 97 139 389 403 420 451 488 653
 $ : int [1:8] 96 168 389 420 451 653 662 773
 $ : int [1:8] 50 117 153 231 409 432 696 708
 $ : int [1:8] 81 145 426 483 667 689 760 769
  [list output truncated]
 - attr(*, "region.id")= chr [1:774] "1" "2" "3" "4" ...
 - attr(*, "call")= language knearneigh(x = coords, k = 8)
 - attr(*, "sym")= logi FALSE
 - attr(*, "type")= chr "knn"
 - attr(*, "knn-k")= num 8
 - attr(*, "class")= chr "nb"</code></pre>
</div>
</div>
<p>Now we can plot the adaptive spatial weight matrix.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(nga_wp<span class="sc">$</span>geometry, <span class="at">border =</span> <span class="st">"lightgrey"</span>, <span class="at">main =</span> <span class="st">"K Nearest Neighbor Matrix"</span>)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(wp_k8, coords, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">cex =</span> <span class="fl">0.2</span>, <span class="at">add =</span> <span class="cn">TRUE</span>, <span class="at">col =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Take-home_Ex1_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="row-standardized-weight-matrix" class="level4">
<h4 class="anchored" data-anchor-id="row-standardized-weight-matrix">Row standardized weight matrix</h4>
<p>We will compute a row standardized weight matrix based on <code>wp_k8</code> by using <code>nb2listw()</code> from <strong>spdep</strong> package.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>wp_rsw <span class="ot">&lt;-</span> <span class="fu">nb2listw</span>(wp_k8, <span class="at">style =</span> <span class="st">"W"</span>, <span class="at">zero.policy =</span> <span class="cn">TRUE</span>)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>wp_rsw</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Characteristics of weights list object:
Neighbour list object:
Number of regions: 774 
Number of nonzero links: 6192 
Percentage nonzero weights: 1.033592 
Average number of links: 8 
Non-symmetric neighbours list

Weights style: W 
Weights constants summary:
    n     nn  S0       S1       S2
W 774 599076 774 174.2812 3155.312</code></pre>
</div>
</div>
</section>
</section>
<section id="global-spatial-autocorrelation-morans-i" class="level3">
<h3 class="anchored" data-anchor-id="global-spatial-autocorrelation-morans-i">Global Spatial Autocorrelation: Moran’s I</h3>
<section id="morans-i-test" class="level4">
<h4 class="anchored" data-anchor-id="morans-i-test">Moran’s I test</h4>
<p>To perform the Moran’s I test, we will use <code>moran.test()</code> from <strong>spdep</strong> package.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">moran.test</span>(nga_wp<span class="sc">$</span><span class="st">`</span><span class="at">wpt non-functional</span><span class="st">`</span>, <span class="at">listw =</span> wp_rsw, <span class="at">zero.policy =</span> <span class="cn">TRUE</span>, <span class="at">na.action =</span> na.omit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Moran I test under randomisation

data:  nga_wp$`wpt non-functional`  
weights: wp_rsw    

Moran I statistic standard deviate = 22.72, p-value &lt; 2.2e-16
alternative hypothesis: greater
sample estimates:
Moran I statistic       Expectation          Variance 
     0.3830962455     -0.0012936611      0.0002862476 </code></pre>
</div>
</div>
<p>Because the p-value of the test is less than 0.05, we reject the null hypothesis that the non-functional water points are spatially random at 95% confident interval. As the Moran statistic is 0.383, greater than 0, we can say that the non-functional water point observations are clustered.</p>
</section>
<section id="monte-carlo-morans-i" class="level4">
<h4 class="anchored" data-anchor-id="monte-carlo-morans-i">Monte Carlo Moran’s I</h4>
<p>To compute 1,000 simulations of Monte Carlo Moran’s I, we will use <code>moran.mc()</code> from <strong>spdep</strong> package.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>mc_moran <span class="ot">=</span> <span class="fu">moran.mc</span>(nga_wp<span class="sc">$</span><span class="st">`</span><span class="at">wpt non-functional</span><span class="st">`</span>,</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">listw =</span> wp_rsw,</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>                    <span class="at">nsim =</span> <span class="dv">999</span>,</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>                    <span class="at">zero.policy =</span> <span class="cn">TRUE</span>,</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>                    <span class="at">na.action =</span> na.omit)</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>mc_moran</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Monte-Carlo simulation of Moran I

data:  nga_wp$`wpt non-functional` 
weights: wp_rsw  
number of simulations + 1: 1000 

statistic = 0.3831, observed rank = 1000, p-value = 0.001
alternative hypothesis: greater</code></pre>
</div>
</div>
<p>As p-value is 0.001 and less than 0.05, we reject the null hypothesis of spatial randomness among the non-functional water point observations. The statistic of the Moran’s I simulations is 0.3831, greater than 0, corroborating the test result that similar non-functional water point observations are clustered.</p>
</section>
<section id="visualzing-monte-carlo-morans-i" class="level4">
<h4 class="anchored" data-anchor-id="visualzing-monte-carlo-morans-i">Visualzing Monte Carlo Moran’s I</h4>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mc_moran<span class="sc">$</span>res)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>      Min.    1st Qu.     Median       Mean    3rd Qu.       Max. 
-0.0577464 -0.0127344 -0.0011002 -0.0002353  0.0109820  0.3830962 </code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(mc_moran<span class="sc">$</span>res,</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">freq =</span> <span class="cn">TRUE</span>,</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">breaks =</span> <span class="dv">20</span>,</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Simulated Moran's I"</span>,</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Histogram of Moran's I Simulation"</span>)</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="dv">0</span>, <span class="at">col =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Take-home_Ex1_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We can see that the min of the Moran’s I value is less than 0, while the max value is 0.38. The Moran’s I data is approaching 1, inferring similar values are clustered. In layman terms, government areas with similar number of non-functional water points tend to be closer together and form some clusters.</p>
</section>
</section>
<section id="global-spatial-autocorrelation-gearys-c" class="level3">
<h3 class="anchored" data-anchor-id="global-spatial-autocorrelation-gearys-c">Global Spatial Autocorrelation: Geary’s C</h3>
<p>The following section will focus on Geary’s C test and Geary’s C Monte Carlo simulation using the functions from <strong>spdep</strong> package.</p>
<section id="gearys-c-test" class="level4">
<h4 class="anchored" data-anchor-id="gearys-c-test">Geary’s C Test</h4>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">geary.test</span>(nga_wp<span class="sc">$</span><span class="st">`</span><span class="at">wpt non-functional</span><span class="st">`</span>, <span class="at">listw =</span> wp_rsw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Geary C test under randomisation

data:  nga_wp$`wpt non-functional` 
weights: wp_rsw 

Geary C statistic standard deviate = 19.419, p-value &lt; 2.2e-16
alternative hypothesis: Expectation greater than statistic
sample estimates:
Geary C statistic       Expectation          Variance 
     0.6045301723      1.0000000000      0.0004147472 </code></pre>
</div>
</div>
<p>Because p-value is 0.001 and less than 0.05, we reject the null hypothesis of spatial randomness among the non-functional water point observations with 95% confident interval. The statistic of the Geary’s C simulations is 0.605, less than 1, we can say that the data tend to cluster among similar observations.</p>
</section>
<section id="monte-carlo-gearys-c" class="level4">
<h4 class="anchored" data-anchor-id="monte-carlo-gearys-c">Monte Carlo Geary’s C</h4>
<p>We will compute 1000 simulations of Geary’s C using <code>geary.mc()</code>.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>mc_geary <span class="ot">=</span> <span class="fu">geary.mc</span>(nga_wp<span class="sc">$</span><span class="st">`</span><span class="at">wpt non-functional</span><span class="st">`</span>, <span class="at">listw =</span> wp_rsw, <span class="at">nsim =</span> <span class="dv">999</span>)</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>mc_geary</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Monte-Carlo simulation of Geary C

data:  nga_wp$`wpt non-functional` 
weights: wp_rsw 
number of simulations + 1: 1000 

statistic = 0.60453, observed rank = 1, p-value = 0.001
alternative hypothesis: greater</code></pre>
</div>
</div>
<p>The result of the simulation corroborates the previous Geary’s C test with p-value less than 0.05 and Geary’s C statistic less than 1.</p>
</section>
<section id="visualizing-monte-carlo-gearys-c" class="level4">
<h4 class="anchored" data-anchor-id="visualizing-monte-carlo-gearys-c">Visualizing Monte Carlo Geary’s C</h4>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mc_geary<span class="sc">$</span>res)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.6045  0.9857  0.9995  0.9987  1.0128  1.0690 </code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(mc_geary<span class="sc">$</span>res,</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">freq =</span> <span class="cn">TRUE</span>,</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">breaks =</span> <span class="dv">20</span>,</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Histogram of Geary's C Simulation"</span>,</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Simulated Geary's C"</span>)</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="dv">1</span>, <span class="at">col =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Take-home_Ex1_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We can see that the min Geary’s C is less than 1, while the max is greater than 1. The Geary’s C data is approaching 0, meaning similar values are clustered. This result again is similar to Moran’s I. We have areas with similar number of non-functional water points clustering together.</p>
</section>
</section>
</section>
<section id="spatial-correlogram-with-morans-i" class="level2">
<h2 class="anchored" data-anchor-id="spatial-correlogram-with-morans-i">Spatial Correlogram with Moran’s I</h2>
<p>We will use <code>sp.correlogram()</code> from spdep package to compute a 6-lag spatial correlogram of non-functional water points.</p>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>MI_corr <span class="ot">&lt;-</span> <span class="fu">sp.correlogram</span>(wp_k8, </span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>                          nga_wp<span class="sc">$</span><span class="st">`</span><span class="at">wpt non-functional</span><span class="st">`</span>, </span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>                          <span class="at">order=</span><span class="dv">10</span>, </span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>                          <span class="at">method=</span><span class="st">"I"</span>, </span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>                          <span class="at">style=</span><span class="st">"W"</span>)</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(MI_corr, <span class="at">main =</span> <span class="st">"Moran's I Correlogram of Non-functional Water Points"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Take-home_Ex1_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<details>
<summary>Show code</summary>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(MI_corr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Spatial correlogram for nga_wp$`wpt non-functional` 
method: Moran's I
            estimate expectation    variance standard deviate Pr(I) two sided
1 (774)   3.8310e-01 -1.2937e-03  2.8625e-04          22.7196       &lt; 2.2e-16
2 (774)   2.4978e-01 -1.2937e-03  1.4428e-04          20.9027       &lt; 2.2e-16
3 (774)   1.7519e-01 -1.2937e-03  9.8557e-05          17.7769       &lt; 2.2e-16
4 (774)   1.1512e-01 -1.2937e-03  7.3007e-05          13.6241       &lt; 2.2e-16
5 (774)   7.3384e-02 -1.2937e-03  5.7171e-05           9.8765       &lt; 2.2e-16
6 (774)   3.3259e-02 -1.2937e-03  4.7493e-05           5.0137       5.338e-07
7 (774)   2.3599e-03 -1.2937e-03  4.1538e-05           0.5669       0.5708000
8 (774)  -2.3438e-02 -1.2937e-03  3.7172e-05          -3.6322       0.0002811
9 (774)  -5.8066e-02 -1.2937e-03  3.4217e-05          -9.7054       &lt; 2.2e-16
10 (774) -9.0732e-02 -1.2937e-03  3.2640e-05         -15.6549       &lt; 2.2e-16
            
1 (774)  ***
2 (774)  ***
3 (774)  ***
4 (774)  ***
5 (774)  ***
6 (774)  ***
7 (774)     
8 (774)  ***
9 (774)  ***
10 (774) ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The higher the lag value, the lower the estimation of Moran’s I value. From lag 8, the values start to be dispersed with Moran’s I estimation less than 0. Except for lag 7, we can reject the null hypothesis of spatial randomness for other lag values.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>